### ISSUE TITLE
failure when size[0] != bufferStride[0] for large, strided transforms

### ISSUE THREAD

**Issue by nschaeff** [DTolm/VkFFT#101]
With strides > size, I observe errors, and I think vkfft does not perform correct fft (or maybe I do something wrong):
  - on nvidia with CUDA: very large errors
  - on amd with HIP: segfault
This happens when the size is large (observed for size>=4096), when 2 kernels are launched for 1 transform (is that what is called 4-step algo?) and with large strides.
For instance, the following fails for nfft=4096, howmany=1024, stride=1028 :

        config.FFTdim = 2; //FFT dimension: 1D, but we use a second dimension to get non-unit strides.
        config.size[0] = howmany;
        config.size[1] = nfft;
        config.bufferStride[0] = stride;
        config.bufferStride[1] = stride * nfft;
        config.omitDimension[0] = 1;		// no FFT on the first dimension.
        config.doublePrecision = 1;

It seems that the low frequencies are correct but the high frequencies are wrong (to be checked more thoroughly).
Note: when run with cuda-memcheck, it works without errors.

**Comment by nschaeff** [comment]
Yes, problem solved. Thank you very much

**Comment by vincefn** [comment]
Hi - just to understand the transform used - you have an array of size (ny, nx)=(4096, 1024) which is transformed along the y-axis. But if you use a stride of 1028>nx wouldn't you always end up with an out-of-bound access ?

**Comment by DTolm** [comment]
@vincefn the array is padded to (4096,1028) in advance.

**Comment by vincefn** [comment]
OK - so that's definitely not a case I could have with pyvkfft.
