### ISSUE TITLE
glsl only

### ISSUE THREAD

**Issue by ZR233** [DTolm/VkFFT#104]
Is there any way to just generate glsl string without any dependences, so that it can be used for wgpu? thanks!

**Comment by DTolm** [comment]
Hello,

Not right now, as VkFFT requires device-specific values to optimise shaders (max number of threads, simd size, shared memory size, etc). I guess it is possible to always ask user for them or use some meaningful defaults. Another issue is that just from glsl code it will be not that easy to determine the grid needed to launch it. As of now, you can get some glsl shaders with keepShaderCode option and use them in your application, but full VkFFT support is a harder undertaking and will have to wait till till the next revision of code that is currently in development.

Best regards,
Dmitrii

**Comment by ZR233** [comment]
> 

Thank you very much!
