### ISSUE TITLE
Event synchronize when using HIP backend

### ISSUE THREAD

**Issue by helloliu-work** [DTolm/VkFFT#106]
Hi,
I tried vkfft on AMD HIP platform. 
I assigned the vkfft kernels to multiple streams, hope to overlap them with each other. 
However, I found that there is a hipEventSynchronize after each kernel, which essentially make the executions sequential.
Is there any way to get rid of these synchronizations? Since I have the pipeline like taskA-fft-taskB on each streams and want to execute asynchronously.
Best Regards

**Comment by DTolm** [comment]
Hello, 

the hipEventSynchronize calls happen only if more than one stream is assigned to the FFT application. Multiple streams can split the workload between them for big systems, but synchronization of them is then needed between axes. Usually, this doesn't speed up the execution though and it is best to have one stream per application. In your case, you should create multiple instances of the VkFFTApplication, each with a different stream specified, then there will be no synchronization between them.

Best regards,
Dmitrii

**Comment by helloliu-work** [comment]
Thanks a lot.
