### ISSUE TITLE
perform FFT batch of 2D arrays by column

### ISSUE THREAD

**Issue by 285639863** [DTolm/VkFFT#108]
Hi，
I'm having some difficulty doing batch fft of 2D arrays by column with Vkfft. When I use VkFFT to perform FFT batch processing on a two-dimensional array row by row, I set numberBatches to the number of rows of the array, and I can get the correct result. When I want to perform FFT on this two-dimensional array by column, the only way I can think of is to transpose the two-dimensional array first, and then continue to set numberBatches as the number of rows for calculation, but this method increases the amount of calculation. I would like to know how can I set the parameters in VkFFT to do this kind of  batch FFT processing？
Thank you，
Best wishes

**Comment by DTolm** [comment]
Hello,

Currently, there is a workaround: you can do this by setting up a 3D system and using omitDimension[0] set to true. This way first dimension size will serve as an innermost batching option. However, it only works for C2C and R2R transforms (not C2R/R2C).

Best regards,
Dmitrii

**Comment by 285639863** [comment]
Thank you very much!
