### ISSUE TITLE
Issue running on macOS via MoltenVK..

### ISSUE THREAD

**Issue by oscarbg** [DTolm/VkFFT#11]
Hi,
I tried to run your library (single precision mode only) under macOS..
just wanted to see FP32 perf of your library on Metal on a RX Vega..
with a pair of trivial fixes code builds but fails to run due to some issue raised by Apple Metal shader compiler upon variable length arrays:
```
program_source:353:29: error: variable length arrays are not supported in Metal
    threadgroup float2 sdata[_891];
```
for more details I opened a MoltenVK issue:
https://github.com/KhronosGroup/MoltenVK/issues/1106
altough seems an issue of MoltenVK/SPIRV-Cross/Metal I share here the problem as maybe you can find a simple workaround in your shaders without degrading current peformance..
feel free to close the issue if not interested on it..
thanks..

**Comment by DTolm** [comment]
Hello,
in most shaders shared memory size is defined through specialization constants, which are specified in the half-compiled shaders. I don't have much experience with MoltenVK, but maybe this is not possible there right now. 
Nothing really prohibits allocation of full 32KB array every time, except that this limits theoretical occupancy (this plays role on some smaller systems like 64x64x64). I attach shaders (single-precision, float folder) which have full shared memory allocated every time, they should solve this, but it is not the best solution. It is possible to specify these constants before the initial compilation, but this will require to perform a full recompilation with glslangvalidator for each fft system size.
[float.zip](https://github.com/DTolm/VkFFT/files/5382747/float.zip)

**Comment by oscarbg** [comment]
Hi,
thanks for informative explanation..
I tested your modified shaders and it works..
Here is the result using MoltenVK:
[res1.txt](https://github.com/DTolm/VkFFT/files/5388230/res1.txt)
Vega Windows result:
[vegafp32.txt](https://github.com/DTolm/VkFFT/files/5388239/vegafp32.txt)
not much bad 15688 score vs 19xxx on Windows (I will attach results when on Windows)

**Comment by DTolm** [comment]
Judging by the issue you opened, it is best to wait until the support for constant array size definition is added. Anyway, it is very interesting that with not many fixes VkFFT can be launched on macOS. Big thanks for trying this out!

**Comment by oscarbg** [comment]
Just recompiled latest version and modified fp16 shaders similarly to obtain MacOS Metal FP16 results (note it just works as 16 bit storage VK extension is supported by MoltenVK):

```
 ./Vulkan_FFT -vkfft 2
VkFFT System: 32x32x1 Buffer: 0 MB avg_time_per_step: 0.049 ms std_error: 0.000 batch: 1000 benchmark: 162
VkFFT System: 64x64x1 Buffer: 0 MB avg_time_per_step: 0.053 ms std_error: 0.000 batch: 1000 benchmark: 602
VkFFT System: 256x256x1 Buffer: 0 MB avg_time_per_step: 0.077 ms std_error: 0.000 batch: 1000 benchmark: 6608
VkFFT System: 1024x256x1 Buffer: 1 MB avg_time_per_step: 0.110 ms std_error: 0.001 batch: 1000 benchmark: 18554
VkFFT System: 512x512x1 Buffer: 1 MB avg_time_per_step: 0.114 ms std_error: 0.000 batch: 1000 benchmark: 17922
VkFFT System: 1024x1024x1 Buffer: 4 MB avg_time_per_step: 0.293 ms std_error: 0.001 batch: 1000 benchmark: 27944
VkFFT System: 4096x1024x1 Buffer: 16 MB avg_time_per_step: 0.808 ms std_error: 0.001 batch: 256 benchmark: 40532
VkFFT System: 2048x2048x1 Buffer: 16 MB avg_time_per_step: 0.884 ms std_error: 0.001 batch: 256 benchmark: 37047
VkFFT System: 4096x4096x1 Buffer: 64 MB avg_time_per_step: 3.551 ms std_error: 0.003 batch: 64 benchmark: 36912
VkFFT System: 64x64x64 Buffer: 1 MB avg_time_per_step: 0.248 ms std_error: 0.000 batch: 1000 benchmark: 8274
VkFFT System: 128x128x128 Buffer: 8 MB avg_time_per_step: 1.189 ms std_error: 0.000 batch: 512 benchmark: 13783
VkFFT System: 256x256x256 Buffer: 64 MB avg_time_per_step: 9.122 ms std_error: 0.005 batch: 64 benchmark: 14368
VkFFT System: 512x256x64 Buffer: 32 MB avg_time_per_step: 2.272 ms std_error: 0.001 batch: 128 benchmark: 28848
VkFFT System: 1024x1024x64 Buffer: 256 MB avg_time_per_step: 18.993 ms std_error: 0.005 batch: 16 benchmark: 27603
VkFFT System: 4096x256x32 Buffer: 128 MB avg_time_per_step: 6.634 ms std_error: 0.006 batch: 32 benchmark: 39513
VkFFT System: 2048x256x256 Buffer: 512 MB avg_time_per_step: 66.238 ms std_error: 0.036 batch: 8 benchmark: 15830
VkFFT System: 4096x4096x8 Buffer: 512 MB avg_time_per_step: 33.709 ms std_error: 0.024 batch: 8 benchmark: 31107
VkFFT System: 32768x64x1 Buffer: 8 MB avg_time_per_step: 0.491 ms std_error: 0.001 batch: 512 benchmark: 33384
VkFFT System: 65536x64x1 Buffer: 16 MB avg_time_per_step: 0.923 ms std_error: 0.000 batch: 256 benchmark: 35486
VkFFT System: 131072x64x1 Buffer: 32 MB avg_time_per_step: 1.812 ms std_error: 0.002 batch: 128 benchmark: 36166
VkFFT System: 262144x64x1 Buffer: 64 MB avg_time_per_step: 3.580 ms std_error: 0.001 batch: 64 benchmark: 36607
VkFFT System: 1048576x64x1 Buffer: 256 MB avg_time_per_step: 15.707 ms std_error: 0.010 batch: 16 benchmark: 33378
VkFFT System: 4194304x64x1 Buffer: 1024 MB avg_time_per_step: 67.418 ms std_error: 0.057 batch: 4 benchmark: 31106
VkFFT System: 8192x8192x1 Buffer: 256 MB avg_time_per_step: 26.285 ms std_error: 0.046 batch: 16 benchmark: 19946
VkFFT System: 16384x16384x1 Buffer: 1024 MB avg_time_per_step: 152.590 ms std_error: 0.075 batch: 4 benchmark: 13743
Benchmark score VkFFT: 24217
Device name: AMD Radeon RX Vega 64 API:1.1.154
```

**Comment by DTolm** [comment]
I have removed all specialization constants in the latest version of VkFFT, so the main problem of MoltenVK support should be solved for VkFFT!

**Comment by oscarbg** [comment]
yes now prebuilt binaries and shaders work by default!
thanks!
