### ISSUE TITLE
OpenCL save compiled binary seems to be broken

### ISSUE THREAD

**Issue by bdenhollander** [DTolm/VkFFT#110]
I can not run benchmark 0 on OpenCL compiled in VS 2019 on Windows 10 unless I comment out lines 38675-701 and 38711. This skips trying to load the cached VkFFT_binary, which was requested by `loadApplicationFromString`, and compiles it every time.

Line 38744 will report a binary size of 9504 bytes but the file that gets written to disk is only 56 bytes. Perhaps the `axis->binary` that is storing the compiled OpenCL program is missed later on when writing various binaries starting at line 40504.

This is on an AMD Radeon RX 6600 using 23.3.2 drivers.

**Comment by DTolm** [comment]
Technically, param_value_size in clGetProgramInfo is "used to specify the size in bytes of memory pointed to by param_value. This size must be ≥ size of return type as described in the table above". param_value is &axis->binary and it is a double pointer, so this should be the correct implementation. Nvidia GPUs I guess just don't care for param_value_size in their implementation, so it works either way.

**Comment by AURRAu** [comment]
-
