### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by elbriggs** [DTolm/VkFFT#116]
I have been trying out vkfft in an application that uses threads with a single hip stream per thread. It runs correctly using rocfft with multiple threads but not with vkfft (a single thread is fine). Is vkfft thread safe? (Could not find any mention of this in the user guide).

**Comment by elbriggs** [comment]
OK I found the reference to disableSetLocale in vkFFT.h but that does not appear to change anything.

**Comment by DTolm** [comment]
Hello,

VkFFT should be thread-safe, apart from the locale changes in sprintf, where you have to manage locale from outside VkFFT on multithreaded systems. You can see an example of VkFFT usage with multiple hip streams here: https://github.com/Biu-G/gromacs-rocm/blob/16d0bbb851025e03e1dae9aaa35b021d5e53683e/src/gromacs/ewald/pme_gpu_3dfft.hip.cpp.

Can you share your VkFFT configuration code so I can try to understand the issue?

Best regards,
Dmitrii

**Comment by elbriggs** [comment]
Hi Dmitrii
  I found something that makes it work. Here is the working configuration code below. It is called during initialization not from a thread. The loop index i is over the number of threads that will be used. When I explicitly set num_streams=1 the code runs correctly. If I do not set it the code will produce incorrect answers. In vkFFT.h it says the default is 1 though?
Thanks Emil

        uint64_t num_streams;//try to submit HIP kernels in multiple streams for asynchronous execution. Default 1


          VkFFTConfiguration vkconf = {};
          vk_plans[i] = {};
          vkconf.FFTdim = 3;
          vkconf.size[0] = lengths[0];
          vkconf.size[1] = lengths[1];
          vkconf.size[2] = lengths[2];
          vkconf.stream = &streams[i];
          vkconf.num_streams = 1;
          vkconf.doublePrecision = 1;
          vkconf.disableSetLocale = 1;
          vkconf.device = &ct.hip_dev;
          vkconf.buffer = (void **)&dev_bufs[i];
          size_t bufSize = (size_t)this->global_basis_alloc * sizeof(std::complex<double>);
          vkconf.bufferSize = &bufSize;
          VkFFTResult resFFT = initializeVkFFT(&vk_plans[i], vkconf);
          if (resFFT != VKFFT_SUCCESS)
              printf("ERROR setting up vkfft.\n");
          else
              printf("Set up vkfft!\n");

**Comment by elbriggs** [comment]
Thanks Dmitri!
