### ISSUE TITLE
How to modify  the stride of w axis?

### ISSUE THREAD

**Issue by zhaohaifei** [DTolm/VkFFT#119]
The stride of w axis is fixed to 1, can i modify it to other value?

**Comment by DTolm** [comment]
Hello,

you can have a workaround for strided FFT (up to 2 dimensions in C2C and R2R) as explained here https://github.com/DTolm/VkFFT/issues/71

The proper support of strided accesses for all dimensions will come at some point later.

Best regards,
Dmitrii
