### ISSUE TITLE
error: empty scalar initializer in VkCommandBuffer commandBuffer = {};

### ISSUE THREAD

**Issue by ozvoz** [DTolm/VkFFT#120]
Dear Dimitrii,

just a minor tittle, there are in vkFFT.h a few lines with

VkCommandBuffer commandBuffer = {};

which result in

error: empty scalar initializer

when using gcc for C projects as empty initializers are not allowed until the C23 standard.
A global replace with

VkCommandBuffer commandBuffer = { 0 };

as already is the case at other locations in the code avoids this error.

**Comment by DTolm** [comment]
Hello,

All of these should be fixed in the develop v1.3 branch that will be merged next week. The corresponding pr fix is https://github.com/DTolm/VkFFT/pull/118.

Best regards,
Dmitrii
