### ISSUE TITLE
Half Precision Support for OpenCL

### ISSUE THREAD

**Issue by tangjinchuan** [DTolm/VkFFT#121]
Dear Dimitri,
Since both Intel and AMD support cl_khr_fp16 while Nvidia is making the support happen (see the info I received from Nvidia today: https://github.com/CNugteren/CLBlast/issues/1#issuecomment-1652149254), could you please consider adding the half support for OpenCL.

Thank you very much!

Best wishes,
Jinchuan Tang

**Comment by DTolm** [comment]
Hello,

It is already enabled for all backends on the develop branch. It will soon be merged into the main one.

Best regards,
Dmitrii

**Comment by tangjinchuan** [comment]
Dear Dmitrii,
Congratulations on the new release!
In the meantime, since so many folders have been introduced for VKFFT instead of a single vkfft.h file, I did manage to fixing compiling issues related to *.h files do not exist. Instead of adding extra folder information onto the makefiles, may I suggest using relative locations such as "../../". e.g. #include "../vkFFT_PlanManagement/vkFFT_HostFunctions/vkFFT_Scheduler.h" instead of #include "vkfft/vkFFT_PlanManagement/vkFFT_HostFunctions/vkFFT_Scheduler.h" .
As a result, users would use it like including a single file vkfft.h in the previous version. I have attached the modified version for your reference. (Please kindly note that I may have commented some OpenCL headers for my project)

Best wishes,
Jinchuan
