### ISSUE TITLE
Is there any documentation that can help to read the code？

### ISSUE THREAD

**Issue by zhaohaifei** [DTolm/VkFFT#122]
I want to learn the code of vkfft, but find it too obscure. Is there any documentation to read?

**Comment by DTolm** [comment]
So far, there is a VKFFT white paper 
https://ieeexplore.ieee.org/document/10036080 
and an API design document 
https://github.com/DTolm/VkFFT/blob/master/documentation/VkFFT_API_guide.pdf

As for the in-depth code comments, they are not there yet, apart from the functions and variables names that somewhat explain what they do. I plan on doing the code documentation in the future, but before 1.3 it was not feasible to do as the codebase structure was changing a lot.

**Comment by zhaohaifei** [comment]
Any way, thank you.
