### ISSUE TITLE
Allow debug builds with cmake -DCMAKE_BUILD_TYPE=Debug

### ISSUE THREAD

**Issue by pknowles** [DTolm/VkFFT#128]
It would be good to avoid the following, so that cmake can be configured for debug builds:

```
set(CMAKE_BUILD_TYPE "Release" CACHE STRING "" FORCE)
```

See: https://stackoverflow.com/a/23916503/1888983

**Comment by DTolm** [comment]
Hello.

The CMake is used to configure the benchmark/precision verification suite. Why would you not want it to be built in Release? The library itself is header-only, so this should not affect the actual usage of it.

Best regards,
Dmitrii

**Comment by al42and** [comment]
> Why would you not want it to be built in Release?

Not sure what's @pknowles's case, but I used the debug build for solving #124. The flow was like: "Our application now crashes. But is it a bug in VkFFT itself or in how we use it? Let's try the benchmark suite. Crashes too? Ok, now we know that it's not our code. Let's run the benchmark suite in debugger and look at the stack trace to avoid any extra noise and abstraction layers." (in the end, there _was_ an unrelated issue with our code, but that's another story)

**Comment by DTolm** [comment]
Ok, but that is one line of code that is needed to change in CMakeLists. The main purpose of the benchmark is to measure the best performance, so it makes sense to force the Release build for this - I think I originally enabled it as there were some performance drops in the cuFFT library and I wanted the comparison to be fair.

**Comment by al42and** [comment]
> Ok, but that is one line of code that is needed to change in CMakeLists. The main purpose of the benchmark is to measure the best performance, so it makes sense to force the Release build for this

Can't argue here.

But it is also not hard to surround this line with `if(NOT CMAKE_BUILD_TYPE)`/`endif()` to allow the users to change the build type with normal CMake means if they so wish, while still using `Release` by default.

**Comment by DTolm** [comment]
True, I can add this in the next update. Thanks!

**Comment by DTolm** [comment]
Dear All,

These guards have been added to the 1.3.2 version.

Best regards,
Dmitrii
