### ISSUE TITLE
[Question] How to pass a `id<MTLCommandQueue>` as a `MTL::CommandQueue` of Metal-Cpp?

### ISSUE THREAD

**Issue by ZJUGuoShuai** [DTolm/VkFFT#131]
**The situation:** I'm developing an iOS Metal App in **Objective-C**. I'm using VkFFT which provides Metal FFTs based on [Metal-Cpp](https://github.com/bkaradzic/metal-cpp).

**What I need:** pass a `id<MTLCommandQueue>` instance from Objective-C world to C++ world as a `MTL::CommandQueue` object so that I can push compute commands to it. **I don't want to create a seperate commmand queue in Metal-Cpp** because using a single command queue can let me keep pushing all commands to it without `waitUntilCompleted`.

After searching the web, I didn't find out how to do that. And [Metal-Cpp](https://github.com/bkaradzic/metal-cpp) doesn't have Issues opened so I can only ask here.

**Comment by DTolm** [comment]
Hello,

I have no experience in how Objective-C - C++ interoperability works, but shouldn't there be some casting available? Maybe @philipturner can help with that question?

Best regards,
Dmitrii
