### ISSUE TITLE
r2c+c2r question

### ISSUE THREAD

**Issue by zhaohaifei** [DTolm/VkFFT#132]
I used the outplace mode when doing r2c+c2r calculations. Refer to sample-15, when r2c, assign r to inputBuffer, and assign c to buffer. If c2r is calculated, shouldn't c be assigned to inputBuffer and r assigned to buffer? Why in the example, c is still assigned to buffer and r is assigned to inputbuffer? I don't quite understand the underlying principle. Can you tell me what happened in detail?

**Comment by DTolm** [comment]
Sample 15 uses inverseReturnToInputBuffer flag in the configuration that makes the order of buffers reversed, meaning c2r code created by the application will return to the inputBuffer.

**Comment by zhaohaifei** [comment]
If I don't use  inverseReturnToInputBuffer flag, should the order be that c is assigned to inputbuffer and r is assigned to buffer?

**Comment by DTolm** [comment]
Yes, this will be the case.
