### ISSUE TITLE
Undefined behaviour when initializing plan

### ISSUE THREAD

**Issue by DejvBayer** [DTolm/VkFFT#134]
Hi,

when function **setConfigurationVkFFT** is called from **initializeVkFFT** in module [vkFFT_InitializeApp.h] https://github.com/DTolm/VkFFT/blob/master/vkFFT/vkFFT/vkFFT_AppManagement/vkFFT_InitializeApp.h), there is line that should reset the app configuration, however it is commented out, so the configuration just works with some random values that lead to segfault. Shouldn't it be uncommented?

```cpp
static inline VkFFTResult setConfigurationVkFFT(VkFFTApplication* app, VkFFTConfiguration inputLaunchConfiguration)  {
	VkFFTResult resFFT = VKFFT_SUCCESS;
	//app->configuration = {};// inputLaunchConfiguration;                              <- this line
	if (inputLaunchConfiguration.doublePrecision != 0)	app->configuration.doublePrecision = inputLaunchConfiguration.doublePrecision;
	if (inputLaunchConfiguration.doublePrecisionFloatMemory != 0)	app->configuration.doublePrecisionFloatMemory = inputLaunchConfiguration.doublePrecisionFloatMemory;

        /* ... */
}
```

Thanks.

Dave

**Comment by DTolm** [comment]
Hello,

Originally I thought the user should zero-initialize the app struct before initialization as to not allow potential memory leaks (for example, if initializeVkFFT is called twice on the same app without freeing resources first).

Now I see that it is possible to add a full app memset to zero in the deleteVkFFT call and add a check for app bytes being zero in the initializeVkFFT call. This should be a better approach compared to setting configuration to zero. 

I will add this in the next update. 

Best regards,
Dmitrii

**Comment by DejvBayer** [comment]
Hi Dmitrii,

thank you for your reply. I am sorry, it was my mistake, I accidentally forgot to zero initialize the app object when I moved from OpenCL to CUDA. After zero initialization everything works fine.

Once again thank you very much.

Best regards,
David

**Comment by DTolm** [comment]
Hello,

I have added the checks for the app being zero and freeing the resources on being deleted. It will be soon merged into the master branch, thanks for suggesting it!

Best regards,
Dmitrii
