### ISSUE TITLE
Please avoid putting binary files (BLOBs) in git

### ISSUE THREAD

**Issue by andreygursky** [DTolm/VkFFT#14]
The appropriate place for archives with precompiled binaries like Vulkan_FFT_CUDA_v1.0.5.zip, Vulkan_FFT_noCUDA_v1.0.5.zip is https://github.com/DTolm/VkFFT/releases.

Thanks.

**Comment by DTolm** [comment]
Thanks for the info! I will restructure the project accordingly with the next update

**Comment by DTolm** [comment]
Done in the last update

**Comment by andreygursky** [comment]
That's great, thank you!
