### ISSUE TITLE
Segmentation fault with 1.3.3

### ISSUE THREAD

**Issue by iyanmv** [DTolm/VkFFT#150]
Hi,

`VkFFT_TestSuite` crashes with a segmentation fault (core dumped) with the latest release (v1.3.3).
I run a `git bisect` and I identified this commit as the culprit: 50c0d4e6dad7ed68ae5479e595a80684ec32e64c

Just in case it is useful, I'm using g++ (GCC) 13.2.1 and I attach the output of [vulkaninfo](https://github.com/DTolm/VkFFT/files/13929852/vulkaninfo.txt).

**Comment by DTolm** [comment]
Hello,

thanks for noticing, the issue should be fixed now. I also remade the latest release to include the fix.

Best regards,
Dmitrii

**Comment by iyanmv** [comment]
Yes, running `VkFFT_TestSuite` on commit [`v1.3.3b`](https://github.com/DTolm/VkFFT/commit/452157d370373b571b18a8c44f6c673bb7021971) works again. Thanks for the quick fix!
