### ISSUE TITLE
Merge DCT and DST into DTT

### ISSUE THREAD

**Issue by DejvBayer** [DTolm/VkFFT#151]
Hi,

I was wondering if it would be possible to merge DCT and DST computation into single DTT type where you could select the right DTT type for each axis (same as FFTW). It would help me a lot, because in our project we mix different DCT and DST types.

Thanks a lot!

David

**Comment by DTolm** [comment]
Hello,

Sure, this is not hard to add. I will keep the legacy functionality and just add another parameter performDTT[fftDim] that will take predefined values VKFFT_REDFTXX/VKFFT_RODFTXX  like FFTW_REDFTXX/FFTW_RODFTXX in FFTW.

Best regards,
Dmitrii

**Comment by DejvBayer** [comment]
That would be awesome! However I would consider naming it performR2R[fftDim] in case any other transforms R2R are added in the future.

Thank you very much.

David

**Comment by DTolm** [comment]
I have added performR2R option. It passed quick simple tests and should work (as it didn't require any new algorithms).

**Comment by davebayer** [comment]
Great job! Thanks a lot.
