### ISSUE TITLE
Forward - Backward FFT

### ISSUE THREAD

**Issue by kleinl** [DTolm/VkFFT#18]
Hey,
first of all thank you for your work. I've come across something which I do not understand.

in Vulkan_FFT.cpp:2837
`p = fftw_plan_dft_1d(benchmark_dimensions[n][0], inputC_double, output_FFTW, 1, FFTW_ESTIMATE);`
you are creating a backwards FFT according to [http://www.fftw.org/fftw3_doc/Complex-One_002dDimensional-DFTs.html](url)

> The fourth argument, sign, can be either FFTW_FORWARD (-1) or FFTW_BACKWARD (+1), and indicates the direction of the transform you are interested in; technically, it is the sign of the exponent in the transform.

but in Vulkan_FFT.cpp:2914
`forward_configuration.inverse = false; //Direction of FFT. false - forward, true - inverse.`
a forward fft is created.

Interestingly the error seems to be quite low even though we're comparing the results of and ifft with the results of an fft which is really confusing to me.

**Comment by DTolm** [comment]
Hello,
I used plus sign for forward and minus sign for inverse transform (reverse of FFTW). I also have the inverse transform normalized (in FFTW it is simply the sign change). I will change it to be conformant with FFTW in the next update.
Best regards,
Dmitrii

**Comment by kleinl** [comment]
Thank you for the quick response!
