### ISSUE TITLE
Arrays of buffer sizes lifetime

### ISSUE THREAD

**Issue by CoffeeExterminator** [DTolm/VkFFT#184]
Hi,
I have found out (the hard way) that the buffer sizes (bufferSize, inputBufferSize, etc.) provided in the configuration as pointers are required even after initialization and thus must be kept alive. Meaning, that if I do something like this
```cpp
config.bufferSize = (uint64_t *) &size
```
The ```size``` variable must exist even after the initialization is completed, which, at least to me, was not the expected behavior (I understand they are in fact arrays since it's possible to use multiple buffers, but still): my assumption was that I can forget about config entirely after the initialization. Could you please clarify if there are any other parameters passed as pointers required after initialization in a similar manner? What about VkFFTLaunchParams? Are the structure or any of its fields required after VkFFTAppend completion? I have done some tests and it seems like they aren't, but asking just in case anyway.

**Comment by fixgoats** [comment]
I was literally just figuring out this was the problem I was having with my code and I feel kind of silly for not having figured it out earlier. I think you just need to apply the normal lifetime heuristics: when you assign any pointer to a field in the config, if the data it points to is stack allocated  and you go out of the scope where the allocation occurs then you have a dangling pointer. This kind of stuff is why RAII is not just a buzzword but actually a useful practice that makes life a whole lot easier.

**Comment by DTolm** [comment]
Hello,

I made a change in the last update on develop branch, that VkFFT now stores the copy of all data that is passed as a pointer. This should solve the issue and now all contents of the config can be deallocated after completion of initializeVkFFT (unless I messed up something). The underlying structs that are passed (like VkDevice) still must not be released before the call to deleteVkFFT.

Best regards,
Dmitrii

**Comment by CoffeeExterminator** [comment]
Hi,
I have tested the develop branch and the issue seems fixed now, thank you.

> The underlying structs that are passed (like VkDevice) still must not be released before the call to deleteVkFFT.

Got a little confused about this. What about VkQueue, VkCommandPool and VkFence used in the config?

**Comment by DTolm** [comment]
I just checked, VkQueue, VkCommandPool and VkFence can be released after the initialization call as they are only used for internal GPU calculations of LUT. Will update the documentation with that. Thanks!

**Comment by CoffeeExterminator** [comment]
Thanks for clarifying!

**Comment by mohawk2** [comment]
None of my business, but... is this now fixed?

**Comment by CoffeeExterminator** [comment]
@mohawk2 
It is, in the develop branch.

**Comment by mohawk2** [comment]
So... can this issue be closed now?

**Comment by CoffeeExterminator** [comment]
I suppose so. I left it open because of the planned documentation update mentioned above, but now that I think about it it's not really related to the issue. So yeah, closing it.
