### ISSUE TITLE
disableReorderFourStep problem with strided FFT ?

### ISSUE THREAD

**Issue by nschaeff** [DTolm/VkFFT#189]
Hello,
I tried the `disableReorderFourStep` option, but doing the backward + forward transform does not give me my original spectral data back.
I perform C2C transforms, but strided (with `omitDimension[0] = 1`).

Follow-up question: does it go along with `performZeropadding[0]=1` and `frequencyZeroPadding = 1` ? (those were not set for the failure reported above)

**Comment by DTolm** [comment]
Hello,

disableReorderFourStep option (as of now) leaves the data in the spectral domain unshuffled after physical to spectral transform and on the spectral to physical transform reads it in this format. So the correct-ordered spectral data with disableReorderFourStep will produce a wrong loop. disableReorderFourStep for this case can be implemented, but probably it is best to focus on more generally useful features than trying to get these 2x memory savings.
The zero-padding also currently doesn't work on the read/write operations where data is processed in the unshuffled format (for other dimensions and data in correct order zero-padding is fine).

Best regards,
Dmitrii

**Comment by nschaeff** [comment]
Thanks for the answer.
Yes, I initially thought it can also bring a performance boost, but if it only memory savings, I don't care either.
