### ISSUE TITLE
syntax error, unexpected SEMICOLON, expecting RIGHT_PAREN or COMMA

### ISSUE THREAD

**Issue by kylexu** [DTolm/VkFFT#20]
Problems occur when I ran sample 9 with a relatively large configuration.size[1], such as 1980, 2048.

Delete one left parenthesis between loc_PI  and %s%s in L4078 fixed the problem. 
https://github.com/DTolm/VkFFT/blob/a8c8f352298d450d7f865b433630fc2e9a062686/vkFFT/vkFFT.h#L4078

**Comment by DTolm** [comment]
Hello,
Thank you for the input, this will be fixed in the next update!
Best regards,
Dmitrii

**Comment by DTolm** [comment]
Closed, as the issue has been resolved.
