### ISSUE TITLE
R2C/C2R 1D 2^12 limitation

### ISSUE THREAD

**Issue by nicoboss** [DTolm/VkFFT#23]
I'm currently switching from cuFFT to VkFFT. I'm using 2^27 large single precision 1D R2C/C2R transformations in cuFFT. In vkFFT single precision 1D R2C/C2R is unfortunately limited to 2^12. Are there any plans to support larger one-dimensional R2C/C2R transformations? If so, I would highly appreciate it. The limitation seems to have to do with the amount of available shared memory but I don’t understand why it can’t be dealt with using multiple axis uploads like done on C2C.

Until this is supported should I just use C2C and fill the complex part with zeros or are there any more efficient ways? It seems like a huge waste of memory access time having to read and write useless zeros from global memory. Could it be possible to only read the real part from memory and just hardcode the complex part to always be zero on FFT and discard the complex part on IFFT? I'm working on a science project about privacy amplification in quantum cryptography where performance is very important. Thanks a lot for making VkFFT. Without it I would be stuck on NVidia GPUs. I’m looking forward to GTC 2021.

**Comment by DTolm** [comment]
I have a long history with multiple upload R2C/C2R and I have spent a lot of time thinking on how to do this properly. The main problem is actually doing the switch step in multiple uploads, which exposes the symmetry. It gets shifted by one element for even sequences and this breaks the memory access pattern. 
Doing R2C by simple padding of complex part will only partially solve the issue. It will work for the first upload of the big sequence, while the consecutive will require full C2C memory. Unless there is also a way to expose the symmetry after the first upload.
I really hope I will find a good solution one day. This is certainly on the to do list.
Best regards,
Dmitrii Tolmachev

**Comment by DTolm** [comment]
Hello,
In the last update, I have added support for multi-upload R2C/C2R sequences - they should have the same limits as the C2C case now. It only works for even sequences for now (non-powers of 2 are supported). Updated sample_15 validates the results of R2C+C2R. If you have other ideas for improvement - feel free to share them!
Best regards,
Dmitrii

**Comment by nicoboss** [comment]
Hello Dmitrii
Thank you so much. You put a lot of work into this! It is absolutely awesome and exactly what I needed. I’m so happy that VkFFT now supports large 1D R2C/C2R. I already tested it and it works perfectly. I will switch to VkFFT in the following days as it has only advantages over cuFFT. 
Best wishes,
Nico Bosshard
