### ISSUE TITLE
2 Minor requests for OpenCL backend..

### ISSUE THREAD

**Issue by oscarbg** [DTolm/VkFFT#26]
Hi,
great to hear VkFFT gains a OpenCL backend! nice work..
unfortunately just wanted to do a quick test on new OpenCL backend and found two issues:
1) seems you don't provide prebuilt OpenCL Windows releases yet (similar to CUDA, VK)..
2) also vulkan_fft command doesn't have a -clfft argument similar so -cufft or -rocfft to perform some basic easy perf testing..
this 2 would be desirable..
thanks..

**Comment by DTolm** [comment]
Hello,
Thanks! There seems to be a lot of interest in OpenCL support, so it is here. 
1. Added executables for easy windows tests. They are similar to other backends in performance. 
2. I thought clfft is abandoned and its codebase is currently continued as rocfft? Not sure if I want to spend time maintaining its benchmarks scripts...
Best regards,
Dmitrii

**Comment by oscarbg** [comment]
Hi,
1. thanks!
2. sorry for my confusion, I misunderstood running with "-vkfft" argument will run benchmarks on Vulkan devices even when compiled using OpenCL API.. the confusion came seeing -cufft and -rocfft arguments..
now "I see/remember" "-vkfft" argument runs on whatever API VKFFT is built..

All OK closing..
