### ISSUE TITLE
An easy way to dump generated kernel?

### ISSUE THREAD

**Issue by masahi** [DTolm/VkFFT#27]
Hi @DTolm, I'm interested in reading generated kernels. Do you have an easy way to dump a kernel specific to input length and other options? Thanks in advance.

**Comment by nicoboss** [comment]
VkFFT will print the generated GLSL kernels to the console if you activate printf("%s", output); which you can find under https://github.com/DTolm/VkFFT/blob/048dd64f46e0ab75663a76e6cca1c43d2448dc1f/vkFFT/vkFFT.h#L7181 The kernels it generates depends on what VkFFTConfiguration you pass to initializeVkFFT.

**Comment by masahi** [comment]
Great! Exactly what I was looking for. 

Thank you very much!

**Comment by DTolm** [comment]
Hello,

The answer given by @nicoboss is correct. To add some more extent to it:
1. GLSL is generated and printed only in the Vulkan backend. In CUDA/HIP/OpenCL backends VkFFT will print kernels in the respective syntax.
2. Code is dependent not only on the configuration but the device parameters as well (it can be different for each device if you have multiple GPUs).
3. The printf on line 7181 prints R2C/C2R decomposition kernel for multi-upload even R2C/C2R mode (sequences with lengths > 2^13). The printf on line 7512 will print the actual FFT kernel code for all axes/uploads.
4. The order of printed kernels is following: inverse FFT x-axis upload 0 -  inverse FFT x-axis upload n - inverse FFT y-axis upload 0 -  inverse FFT y-axis upload n - inverse FFT z-axis upload 0 -  inverse FFT z-axis upload n - forward FFT (similarly).

Best regards,
Dmitrii

**Comment by masahi** [comment]
@DTolm Thank you, very useful!
