### ISSUE TITLE
cuFFT benchmark synchronizing too often

### ISSUE THREAD

**Issue by llukas** [DTolm/VkFFT#3]
Hello,

I noticed there is sync after each `cufftExec` call in the timing loop:

https://github.com/DTolm/VkFFT/blob/d0fb7d9167b8700b88ff36b82d0985e6b2482d80/benchmark_cuFFT.cu#L67
https://github.com/DTolm/VkFFT/blob/d0fb7d9167b8700b88ff36b82d0985e6b2482d80/benchmark_cuFFT.cu#L69
https://github.com/DTolm/VkFFT/blob/d0fb7d9167b8700b88ff36b82d0985e6b2482d80/benchmark_cuFFT.cu#L133
https://github.com/DTolm/VkFFT/blob/d0fb7d9167b8700b88ff36b82d0985e6b2482d80/benchmark_cuFFT.cu#L135

are those synchronizations necessary? It would be sufficient to do single synchronization after the loop. This would also make performance comparison apples-to-apples as VkFFT issues commands and then waits to complete all of them.

Best regards,
Lukasz

**Comment by DTolm** [comment]
Hello, 
yes, this seems to be correct. This will not affect big systems and will bring small ones to the same performance lavel as vkFFT. I will update the benchmark script and plots. 
There is still a problem that cuFFT performs the unnormalized FFT, so after this benchmark the result will most likely be NaN. Adding kernel normalization will again kill cuFFT performance.
Thanks for the correction!
Best regards,
Dmitrii

**Comment by DTolm** [comment]
Updated cuFFT benchmark. No normalization, so cuFFT results will be out of bounds. Now small systems are in line with vkFFT results. Also, side note, this led to me finding out that Nvidia GPUs with compute capability >=6.0 have 32bit coalesced memory access, so there is a performance update to medium sized systems attached to the update.
Best regards,
Dmitrii

**Comment by llukas** [comment]
Thanks for update!
