### ISSUE TITLE
Incorrect C2R inplace transform when using Bluestein algorithm

### ISSUE THREAD

**Issue by vincefn** [DTolm/VkFFT#44]
Hi @DTolm, I think I've found a corner case which gives incorrect results with the latest code.

This is specifically when using the C->R inplace transform with the Bluestein transform (e.g. an original 512x510+2 array, with 510=2x3x5x17). The resulting array does not correspond at all to the original array after doing a R2C+C2R transform.

The forward calculation is OK, as is the out-of-place R2C+C2R transform for a 512x510 array.

In my exhaustives tests in pyvkfft, all others pass.

**Comment by DTolm** [comment]
Hello,

This issue should be fixed in the latest release. Thanks for pointing it out!

Best regards,
Dmitrii Tolmachev

**Comment by vincefn** [comment]
Thanks - all tests pass now !
