### ISSUE TITLE
DCT type 2 and 3 results

### ISSUE THREAD

**Issue by vincefn** [DTolm/VkFFT#45]
Hi @DTolm - as discussed a few weeks ago I checked the result of the DCT against scipy, and found an inversion of results with respect to vkfft for types 2 and 3. Even if DCT is not the main focus of the library, I've done some further checks using a direct calculation from the formula, and still the discrepancy persists.

Here is the graph of the calculation of the DCT with calculations from `pyvkfft`, `scipy.fft.dct` and a direct calculation (labelled `dct`). As you can see the direct calculations match the results from scipy, but exchange the results for types 2 and 3 for pyvkfft:

![image](https://user-images.githubusercontent.com/4380511/130368017-cf991faa-de4a-464f-9341-4d7d621fad30.png)

The code used for the calculations was:
``` python
dct_type = 3  
app = VkFFTApp(x.shape,x.dtype,dct=dct_type)
x_cu = cua.to_gpu(x)
app.fft(x_cu)
# scipy
x_scipy = dctn(x, type=dct_type)

# Direct calculation
N = len(x)
y = np.empty_like(x)
n = np.arange(N)
if dct_type == 2:
    for k in range(N):
        y[k] = 2 * (x * np.cos(np.pi/N*(n+0.5)*k)).sum()
elif dct_type == 3:
    for k in range(N):
        y[k] = x[0] + 2 * (x * np.cos(np.pi/N*n*(k+0.5)))[1:].sum()
elif dct_type == 4:
    for k in range(N):
        y[k] = 2 * (x * np.cos(np.pi/N*(n+0.5)*(k+0.5))).sum()
```
You can also test that [in a working colab notebook](https://colab.research.google.com/drive/1rxRVX1Q3cSL1qJ3mEj5grIWFvhfbNTJr?usp=sharing) with all the libraries installed.

PS: in the documentation's equation for DCT3 (2.3.3 page 8) I think the sum should begin at n=1.

By the way **thanks a lot** for the documentation !

**Comment by DTolm** [comment]
You are correct, I double-checked the FFTW definition and it seems that I have been using DCT-II and III exchanged from the beginning. Should be fixed now (the typo in the documentation as well).

**Comment by vincefn** [comment]
All good now, thanks !
![image](https://user-images.githubusercontent.com/4380511/130407020-6350ba72-baae-47f8-8af0-757e45c20ca2.png)
