### ISSUE TITLE
Numerical issue with some Bluestein FFT dimensions

### ISSUE THREAD

**Issue by vincefn** [DTolm/VkFFT#49]
Dear @DTolm, I think I found an issue when performing 2D FFT with some non-radix dimensions.

Here is the comparison between the VkFFT 2D complex64 FFT and the same from numpy, for a 1208x1208 array (1208=2**3 * 151):

![image](https://user-images.githubusercontent.com/4380511/139243126-c09de8ec-b7db-4700-af25-722d01d697d5.png)

You can see (zoom in the image) that there is a strong vertical central streak which is not present in numpy (much less intense). And after doing the FFT+iFFT there are horizontal streaks compared to the original array.

**Comment by DTolm** [comment]
Hello,
This issue should be resolved now, thanks for bringing it up!
Best regards,
Dmitrii

**Comment by vincefn** [comment]
Hi Dmitrii, thanks a lot for quick fix ! Now all pyvkfft unit tests pass (including DCT ones which I just added) :-)

I may have found some R2C accuracy issues with ndim>1, but maybe specific to Iris GPU. I'll open another issue if I manage to narrow it down...
