### ISSUE TITLE
Necessary to bundle glslang?

### ISSUE THREAD

**Issue by zachjweiner** [DTolm/VkFFT#54]
I was wanting to submodule VkFFT in a project. It's probably better practice than manually copying the header all the time - would make it easier to update or pin to specific commits, etc. (Especially after the refactoring into multiple files that you mentioned.)

I balked at the size of the repo - the source files are 45MB, 90% of which is the bundled glslang-master directory. My understanding is that it's only there for benchmarks, etc., and only for the Vulkan backend at that. Would you consider changing the workflow to clone the glslang repo when needed? (I have no experience with cmake, but it seems like it even has a [built-in way](https://cmake.org/cmake/help/git-stage/module/ExternalProject.html) to do so.)

**Comment by DTolm** [comment]
Hello,
I have removed glslang files from the repository, it will be now downloaded only in the Vulkan backend.

**Comment by zachjweiner** [comment]
Thanks very much for considering and implementing this suggestion!
