### ISSUE TITLE
Improve cooperation with C++ environments

### ISSUE THREAD

**Issue by elfring** [DTolm/VkFFT#6]
[Some code from C source files](https://github.com/DTolm/VkFFT/blob/68b707955953aa50d997a47233b2d9726466cc30/lib/vkFFT.h#L1 "Update candidate") should be wrapped by the setting “[`extern "C"`](https://isocpp.org/wiki/faq/mixing-c-and-cpp#include-c-hdrs-personal "How can I modify my own C header files so it’s easier to #include them in C++ code?")” for C++ tools, shouldn't it?

**Comment by DTolm** [comment]
I have added extern "C", as well as fixing rest of non-C99 code in vkFFT.h (gcc can compile vkFFT.h)

**Comment by elfring** [comment]
Thanks for your source code adjustment.

-----

Would you ever like to choose a build configuration which would take only C++ environments into account?

**Comment by DTolm** [comment]
There is no C++ functionality that can't be done in C in vkFFT.h header file at this moment. Once most other issues are fixed and overall design of the application is more refined, this may be helpful.

**Comment by elfring** [comment]
:crystal_ball: I imagine that there might be software users who would occasionally like to apply a C++ only programming interface (instead of the default C API).

**Comment by DTolm** [comment]
There are not that many differences between what was before and what is implemented now. It is better to have a single API for now and avoid branching
