### ISSUE TITLE
MetalFFT

### ISSUE THREAD

**Issue by philipturner** [DTolm/VkFFT#61]
I saw your comment in Apple Developer Forums and gave some insight. If you’re interested in carrying on my work, we can discuss here which is more convenient than Apple Developer Forums.

**Comment by philipturner** [comment]
> It is a nice attempt, though the algorithms employed in VkFFT are more sophisticated and are designed to work on any modern GPU.

You already interact with CUDA in this repository, which does not work on every GPU. I was thinking that you could start out using MoltenVK, which will be sub-optimal. Then, you make a real port to Metal just like you did for CUDA. The algorithms are what I struggle with, while you struggle with using the Metal API, correct?

> You can try the OpenCL backend of it and see for yourself.

OpenCL has major CPU driver call overhead and is deprecated by Apple. And, I'm not interested in investing my time toward learning an outdated API. Metal is closer to CUDA than anything in terms of performance. It's more suited to general-purpose compute than OpenCL, once you know how to use it. I had to learn it to seriously optimize GPGPU stuff [scene color reconstruction](https://github.com/philipturner/scene-color-reconstruction).

> to understand how C/Swift interop

C/Swift interop works great; you just have to bind using Swift functions that have an `@convention(c)` interface. I did that all the time for [Swift-Colab](https://github.com/philipturner/swift-colab) to interact with CPython. You might even learn it when working with MoltenVK.

> P.S. A small hint, you don't use local/shared memory so every radix butterfly calculation performs a full buffer copy to the chip

About the threadgroup memory optimization - I spent way too much time perfecting an initial prototype. I spent 90% of the time debugging, then got burnt out by the time I had to do real optimizations. If I wanted to continue, I would have explored all sorts of optimizations like using threadgroup memory. I thought you could continue my work because you won't lose motivation for this.

**Comment by DTolm** [comment]
> You already interact with CUDA in this repository, which does not work on every GPU. I was thinking that you could start out using MoltenVK, which will be sub-optimal. Then, you make a real port to Metal just like you did for CUDA. The algorithms are what I struggle with, while you struggle with using the Metal API, correct?

CUDA is not a requirement of VkFFT. It is one of the numerous supported backends, like Vulkan/HIP/OpenCL. When you compile OpenCL code, it won't use CUDA, and will work directly on Apple machines. Vulkan backend also doesn't use CUDA and can use MoltenVK to work on Apple as well. I don't struggle, I just haven't used it at all. 

> OpenCL has major CPU driver call overhead and is deprecated by Apple. And, I'm not interested in investing my time toward learning an outdated API. Metal is closer to CUDA than anything in terms of performance. It's more suited to general-purpose compute than OpenCL, once you know how to use it. I had to learn it to seriously optimize GPGPU stuff for [scene color reconstruction](https://github.com/philipturner/scene-color-reconstruction).

Deprecated, but still supported for some reason, even on new devices. A fair choice not to learn it, but a lot of people have a different opinion on OpenCL, so I support it as a backend option. I was suggesting just running VkFFT benchmarks to see performance comparison for yourself.

> C/Swift interop works great; you just have to bind using Swift functions that have an @convention(c) interface. I did that all the time for [Swift-Colab](https://github.com/philipturner/swift-colab) to interact with CPython. You might even learn it when working with MoltenVK.

Great, means I can continue to keep VkFFT a C project.

> About the threadgroup memory optimization - I spent way too much time perfecting an initial prototype. I spent 90% of the time debugging, then got burnt out by the time I had to do real optimizations. If I wanted to continue, I would have explored all sorts of optimizations like using threadgroup memory. I thought you could continue my work because you won't lose motivation for this.

Good then that I started two years ago and all algorithms are already implemented. Thought you might be interested to check out what you would have to implement next if you chose to continue.

**Comment by philipturner** [comment]
> CUDA is not a requirement of VkFFT.

What I was saying is that since you've already made a backend for CUDA, you can make a backend for Metal as well. Metal is probably the easiest GPGPU API to learn, easier than Vulkan, DirectX, OpenCL. Apple made C++ bindings for Metal that could easily integrate into your existing code.

> Great, means I can continue to keep VkFFT a C project.

You can use entirely C for the initial stages of debugging the port to Apple platforms. But if you want favorable performance, you have to eventually transition to C++ or Swift to use Metal. For example, if you can manage to borrow an iPad from someone, you can do this:
- Wrap the sub-optimal OpenCL/MoltenVK C code in a Swift package
- Run that on iPad Swift Playgrounds. Once that's sufficiently debugged, upgrade to native Metal code. 
- You can avoid learning Metal Shading Language as well. SPIR-V compiles to MSL and Apple ported the Metal compiler to Windows.

> Thought you might be interested to check out what you would have to implement next if you chose to continue.

If I had the motivation, I could translate your Vulkan and CUDA shaders to Metal right now. Then, I'd refactor MetalFFT to use them. But I'm spending my time resurrecting Swift for TensorFlow. Maybe that will change two years down the road. If this is to pan out right now, you need to be the one devoting serious time to this effort. 

I do have a few ideas in mind as to how I could help you. For example, you can't access Apple devices, but I might be able to set up my Intel Mac mini as a sort of virtual machine. You run scripts over the internet, just like how Google Colab works. Don't worry about being restricted to an iGPU; I can port to dGPUs later on. The gist is that I have the physical and experiential resources to pull this off, but not the time resources.

All you have to make is the initial, fully debugged port to native Metal. Then, I could fine-tune the final product or translate any C++/Objective-C code to Swift. Also, I'll translate SPIR-V to MSL for assembly-level optimization. I'll maintain it in my MetalFFT repository indefinitely. We could link to each other's READMEs to show attribution for credit.

**Comment by DTolm** [comment]
Thanks for your implementation suggestions!

> If I had the motivation, I could translate your Vulkan and CUDA shaders to Metal right now. Then, I'd refactor MetalFFT to use them. But I'm spending my time resurrecting Swift for TensorFlow. Maybe that will change two years down the road. If this is to pan out right now, you need to be the one devoting serious time to this effort.

There are no shaders shipped with my code, they are generated at run time and platform-specific. I will check on how Metal compares to Vulkan and come back to this issue once I have an update. Thanks!

**Comment by DTolm** [comment]
Here are the benchmark results of M1 Pro with OpenCL backend (the latest VkFFT version, no adjustments). The peak bandwidth of 174GB/s is pretty impressive for a mobile GPU with low power consumption. Also, compute capabilities of this chip seem to be on a similar level as the code has the same bandwidth-dominated execution time scaling as big GPUs. There is also ~16MB of high-level cache that can be utilized by GPU so if a system fits in it, the effective bandwidth can be 2x higher. Bluestein sequences (big primes) work at 1/4 - 1/2 of the bandwidth, which is a great result. Double precision tests didn't work out of the box.

Best regards,
Dmitrii

[m1pro_vkfft_test0.txt](https://github.com/DTolm/VkFFT/files/8176502/m1pro_vkfft_test0.txt)
[m1pro_vkfft_test3.txt](https://github.com/DTolm/VkFFT/files/8176503/m1pro_vkfft_test3.txt)
[m1pro_vkfft_test4.txt](https://github.com/DTolm/VkFFT/files/8176504/m1pro_vkfft_test4.txt)
[m1pro_vkfft_test6.txt](https://github.com/DTolm/VkFFT/files/8176506/m1pro_vkfft_test6.txt)
[m1pro_vkfft_test7.txt](https://github.com/DTolm/VkFFT/files/8176507/m1pro_vkfft_test7.txt)

**Comment by philipturner** [comment]
Congratulations on running the benchmarks! They seem very promising. How long do you expect to have access to the M1 Pro device?

> Double precision tests didn't work out of the box.

The Apple GPU architecture doesn't support double precision - only single precision. It also supports half precision, but Apple restricts that from OpenCL and only exposes it to Metal. They also limit maximum threadgroup size to 256 in OpenCL but allow up to 1024 in Metal.

> ~16MB of high-level cache

M1 Pro has 32 MB of system-level cache. M1 Max has 64 MB and M1 has 16 MB.

> with OpenCL backend (the latest VkFFT version, no adjustments)

Previously, I didn't favor OpenCL because Apple deprecated it in favor of Metal. Apple were the ones who made OpenCL in the first place, and they gave up on it. Also, I have read stuff that suggests OpenCL driver latencies are terrible. Metal's latencies are already quite difficult to work around for my current project. I imagine that Apple puts even less effort into optimizing their OpenCL backend than Intel and AMD.

After working with [DLPrimitives](https://github.com/artyom-beilis/dlprimitives), OpenCL seems like a reasonable solution. If driver latencies are never a bottleneck, you should be fine. There are still some features like half-precision and hardware-accelerated matrix multiplication that are only available to Metal. Is there a way to profile driver latencies and weigh the ups and downs of pursuing a native Metal backend?

**Comment by philipturner** [comment]
> Double precision tests didn't work out of the box.

I have a lot of experience emulating double precision operations on a GPU. It’s around 20 clock cycles per add or multiply with 48 bits of mantissa. I could recommend a few research papers and show you my previous experimentation.

**Comment by philipturner** [comment]
Is it a 14-core or 16-core M1 Pro? And is it 16 GB or 32 GB memory?

**Comment by DTolm** [comment]
> Congratulations on running the benchmarks! They seem very promising. How long do you expect to have access to the MacBook Pro?

That was my friend's laptop, so it is good for benchmarks, but not for development.

>The Apple GPU architecture doesn't support double precision - only single precision. I have a lot of experience emulating double-precision operations on a GPU. It’s around 20 clock cycles per add or multiply with 48 bits of mantissa.

That's a bit disappointing. Emulating double precision will kill performance on this GPU to the level of unusable, I am afraid, not sure if there will even be demand for that.

 >M1 Pro has 32 MB of system-level cache. M1 Max has 64 MB and basic M1 has 16 MB. 

So my estimation was correct.

>After working with [DLPrimitives](https://github.com/artyom-beilis/dlprimitives), OpenCL seems like a reasonable solution. If driver latencies are never a bottleneck, you should be fine.

Unless you launch really small kernels, driver latencies are not that big of an issue (which is the case for FFTs). Most likely Metal backend results will be similar to those of OpenCL. Metal and DirectX backends are needed for more people to use code in their projects.

> Is it a 14-core or 16-core M1 Pro? And is it 16 GB or 32 GB memory?

I will need to ask about that.

**Comment by psobolewskiPhD** [comment]
For comparison, I have a MBPro M1 (regular, 8 core GPU, 16 GB RAM).
I cloned the repo and edited CMakelists to set backend `3`, then did `cmake .` and `make`.
Running the same tests as above gives ~1/2 the performance, so seems like @DTolm your M1Pro was the 16 core GPU one.

[m1_test7.txt](https://github.com/DTolm/VkFFT/files/8238103/m1_test7.txt)
[m1_test6.txt](https://github.com/DTolm/VkFFT/files/8238104/m1_test6.txt)
[m1_test4.txt](https://github.com/DTolm/VkFFT/files/8238105/m1_test4.txt)
[m1_test3.txt](https://github.com/DTolm/VkFFT/files/8238106/m1_test3.txt)
[m1_test0.txt](https://github.com/DTolm/VkFFT/files/8238108/m1_test0.txt)

CMake output:
<details>

```
-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - found
-- Found OpenCL: /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/OpenCL.framework (found version "1.2") 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/piotrsobolewski/dev/VkFFT
```

</details>

I know I had MoltenVK working at one point as a backend, but now I can't figure out how to get things linked (find_package(Vulkan REQUIRED) is failing)

**Comment by philipturner** [comment]
> Unless you launch really small kernels, driver latencies are not that big of an issue

I concede. My mindset was just fixated on minimizing the driver latencies as much as possible. When I made MetalFFT, I wanted to make a backend for a machine learning framework. For RNNs and sequential algorithms, driver overhead could become the biggest concern and make GPU slower than CPU. But that's not a typical use case for GPGPU.

> Emulating double precision will kill performance on this GPU to the level of unusable, I am afraid, not sure if there will even be demand for that.

That assumption may be incorrect. An FMA is 3 cycles at single precision. For emulated double precision, the fastest solution is separate add and multiply, taking 41 cycles. For reference, the Intel/AMD GPU architecture gives FP64 1/4 the compute capacity of FP32, and Nvidia gives 1/64 the capacity.
- M1 Max @ 10 TFLOPS (FP32), native FP32 -> 3333 billion FMA's per second
- M1 Max @ 10 TFLOPS (FP32), emulated FP64 -> 240 billion FMA's per second
- AMD GPU @ 10 TFLOPS (FP32), native FP64 -> 830 billion FMA's per second
- Nvidia GPU @ 10 TFLOPS (FP32), native FP64 -> 50 billion FMA's per second

We could make a comparison to memory bandwidth. An FMA @ FP64 involves 32 bytes transferred over main memory (3 inputs, 1 output, each 8 bytes). For bandwidth to match throughput on M1 Max, it would need 240 billion * 32 = 7680 GB/s bandwidth. But the theoretical peak bandwidth is 400 GB/s. By what factor would doing butterflies in threadgroup memory decrease the bandwidth requirement, when L3 cache is not warmed yet?

Also, compare CPU performance. ARM64 (Apple silicon) can work on 128-bit vectors using ARM NEON. Intel Xeon can work with 512-bit vectors. Both numbers below assume 3 cycles/FMA and 3 GHz clock speed.
- ARM CPU @ 12 GFLOPS (FP32), native FP64 -> 2 billion FMA's per second per CPU core
- Intel CPU @ 48 GFLOPS (FP32), native FP64 -> 8 billion FMA's per second per CPU core

For Apple M1 Max using all 8 performance cores simultaneously, that's 16 billion FMA's per second on CPU, but 240 billion FMA's on GPU. vkFFT could be up to 15x faster than Accelerate. Since compute now becomes the dominating bottleneck, it's likely you will reach 100% utilization of the emulated FP64 compute capacity (GPU). The same could not be said about CPU.

**Comment by philipturner** [comment]
The research papers I studied for how to emulate FP64 were using Nvidia GPUs. They wanted to increase FP64 throughput past what was natively supported on Nvidia. From the figures above, that would be a (240 billion) / (50 billion) factor improvement. This would make vkFFT faster on both Apple and Nvidia GPUs.

**Comment by philipturner** [comment]
> By what factor would doing butterflies in threadgroup memory decrease the bandwidth requirement, when L3 cache is not warmed yet?

For this, I meant main memory bandwidth. As in will it exceed 400 GB/s? Threadgroup memory allows performing multiple stages in one shader call, decreasing how many numbers must be transferred over main memory. But how many stages does it do in one shader call? For example, if it did 10 at once, you might divide 7680 GB/s by 10 to get 768 GB/s main memory bandwidth required. In that case, main memory bandwidth would remain the biggest bottleneck. My calculation wasn't quite relevant for FFTs, but you get the general idea.

> All in all, the math logic is abstracted in VkFFT. So, in general it should be possible (and not that hard) to add custom FMA definitions there.

I dug up my previous work on double precision. While creating MultiPendulum, I encountered some issues with converting to and from split double format - unexpected NaNs. Also, the biggest issue in MultiPendulum was lack of dynamic range, not lack of precision. Split double has the same dynamic range as FP32. I gave up on using GPU for MultiPendulum and switched back to CPU shortly after.

https://gist.github.com/philipturner/9d349a6a4d3aae3e374ff57d63db6c32

https://dl.acm.org/doi/pdf/10.22360/SpringSim.2016.HPC.032

http://andrewthall.org/papers/df64_qf128.pdf

**Comment by DTolm** [comment]
> Threadgroup memory allows performing multiple stages in one shader call, decreasing how many numbers must be transferred over main memory. But how many stages does it do in one shader call?

It can do all of them with a single read/write to global memory for sequences up to ~8192. Up to 2^22 it will need two, and up to 2^30 it will need three. I had my doubts about performance in double precision emulation as when I tried to do polynomial approximation for sincos in double precision, it killed performance (using lookup tables was a much better solution, even though it increased number of memory transfers).

> Also, the biggest issue in MultiPendulum was lack of dynamic range, not lack of precision.

So it will not be IEEE-754 compliant. Also there may be a big difference in orders (especially as 0 corner element is a sum of all inputs and it causes some troubles in half-precision as it has even smaller range). Not sure how actual users of double precision will like it.

**Comment by philipturner** [comment]
> So it will not be IEEE-754 compliant. Also there may be a big difference in orders (especially as 0 corner element is a sum of all inputs and it causes some troubles in half-precision as it has even smaller range). Not sure how actual users of double precision will like it.

At this point, there's nothing much I can do to contribute to your project. Thanks for humoring me though!

**Comment by philipturner** [comment]
I modified the README of [MetalFFT](https://github.com/philipturner/metal-fft) to officially put it in archive mode, and direct viewers to your repository.
