### ISSUE TITLE
[1.2.17] Poor performance with power of 2 FFTs

### ISSUE THREAD

**Issue by Clemasteredge** [DTolm/VkFFT#64]
Hello,

First, I would like to thank the author for this incredible library! The amount of work put into it is just impressive.

I recently upgraded from v1.2.3 to v1.2.17 and am experiencing odd performance with some power of 2 2D C2C FFTs in FP32 with the Vulkan backend.

I wrote a custom benchmark script with different formatting and to focus on the FFT sizes I'm interested in. I tested on both a Quadro P3200 Max-Q and RTX A5000 and both exhibit a similar odd performance with some power of 2 sizes (see below).
In particular, 2048x2048, 4096x2048 and 4096x4096 sizes are about 2x slower than before.

Note that the results are fine in FP16.

Anybody else experiencing the same behavior?

**Results v1.2.17**
User 20 - VkFFT FFT + iFFT C2C 2D benchmark in fp32 (single) precision
          System Size    Memory      Time (msec)    Bandwidth (GB/s)
         *  256x 256:      0 MB   -    0.0621   -   62.9
         *  384x 384:      1 MB   -    0.1308   -   67.2
         *  512x 512:      2 MB   -    0.1303   -   120.0
         *  729x 512:      2 MB   -    0.2266   -   98.2
         *  768x 512:      3 MB   -    0.2080   -   112.7
         * 1024x 512:      4 MB   -    0.2538   -   123.1
         *  768x 768:      4 MB   -    0.3805   -   92.4
         * 1024x1024:      8 MB   -    0.5607   -   111.5
         * 1536x 800:      9 MB   -    0.8055   -   90.9
         * 1536x1024:     12 MB   -    1.1140   -   84.2
         * 1920x1200:     17 MB   -    1.5568   -   88.2
         * 1536x1536:     18 MB   -    1.7236   -   81.6
         * 2048x1024:     16 MB   -    1.1279   -   110.8
         * 2048x1536:     24 MB   -    1.7760   -   105.6
         *** 2048x2048:     32 MB   -    5.5205   -   45.3**
         * 2187x2187:     36 MB   -    3.8770   -   110.3
         * 2401x2401:     43 MB   -    4.2725   -   120.6
         * 3072x2048:     48 MB   -    11.9722   -   31.3
         * 3125x2048:     48 MB   -    11.1565   -   34.2
         *** 4096x2048:     64 MB   -    14.2918   -   35.0**
         * 4096x2187:     68 MB   -    6.4400   -   124.4
         * 3840x2400:     70 MB   -    6.5511   -   125.8
         * 4096x2401:     75 MB   -    6.8873   -   127.7
         * 3125x3125:     74 MB   -    7.0705   -   123.5
         *** 4096x4096:    128 MB   -    39.5914   -   25.3**
         * 6144x4096:    192 MB   -    73.0597   -   20.5
         * 6250x4096:    195 MB   -    71.7578   -   31.9
         * 6561x4096:    205 MB   -    74.8663   -   32.1
Benchmark score VkFFT: 9697
Device name: Quadro P3200 with Max-Q Design API:1.2.4634968666771816623

**Results v1.2.3**
User 20 - VkFFT FFT + iFFT C2C 2D benchmark in fp32 (single) precision
          System Size    Memory      Time (msec)    Bandwidth (GB/s)
         *  256x 256:      0 MB   -    0.0575   -   68.0
         *  384x 384:      1 MB   -    0.1526   -   57.6
         *  512x 512:      2 MB   -    0.1650   -   94.7
         *  729x 512:      2 MB   -    0.2114   -   105.3
         *  768x 512:      3 MB   -    0.2259   -   103.7
         * 1024x 512:      4 MB   -    0.2400   -   130.2
         *  768x 768:      4 MB   -    0.6451   -   54.5
         * 1024x1024:      8 MB   -    0.5310   -   117.7
         * 1536x 800:      9 MB   -    0.9523   -   76.9
         * 1536x1024:     12 MB   -    1.0662   -   87.9
         * 1920x1200:     17 MB   -    2.0508   -   67.0
         * 1536x1536:     18 MB   -    2.6054   -   54.0
         * 2048x1024:     16 MB   -    1.0648   -   117.4
         * 2048x1536:     24 MB   -    1.7528   -   107.0
         * 2048x2048:     32 MB   -    2.9182   -   85.7
         * 2187x2187:     36 MB   -    3.6368   -   117.6
         * 2401x2401:     43 MB   -    5.4842   -   94.0
         * 3072x2048:     48 MB   -    7.3460   -   51.0
         * 3125x2048:     48 MB   -    6.4068   -   59.5
         * 4096x2048:     64 MB   -    7.1512   -   69.9
         * 4096x2187:     68 MB   -    6.0833   -   131.7
         * 3840x2400:     70 MB   -    6.2069   -   132.8
         * 4096x2401:     75 MB   -    6.5162   -   134.9
         * 3125x3125:     74 MB   -    6.6824   -   130.7
         * 4096x4096:    128 MB   -    17.6925   -   56.5
         * 6144x4096:    192 MB   -    28.7490   -   52.2
         * 6250x4096:    195 MB   -    34.8158   -   65.7
         * 6561x4096:    205 MB   -    36.8910   -   65.1
Benchmark score VkFFT: 10290
Device name: Quadro P3200 with Max-Q Design API:1.2.4630388762755465391

**Comment by DTolm** [comment]
Hello,

not sure why it got closed automatically, but I have fixed the strided register overutilization kernels being launched with lower coalescing than possible. This was the issue and now code for those kernels should be similar to 1.2.3.

Best regards,
Dmitrii

**Comment by Clemasteredge** [comment]
Hello,

That's fantastic, thank you so much!
I confirm the issue is fixed with the latest 1.2.17.

Cheers,
Clement
