### ISSUE TITLE
Questions on a potential SYCL port

### ISSUE THREAD

**Issue by mreineck** [DTolm/VkFFT#65]
I have been working quite a bit on FFTs in the past, but only started recently to develop for GPUs, using SYCL (since that's closest to the C++ world I'm used to, and promises to be somewhat more portable than CUDA and friends).

One thing that SYCL is sorely lacking is an FFT implementation, and I'm wondering if a port of VkFFT to SYCL is possible, at least in theory. As far as I understand, VkFFT currently generates GPU code on the fly for any requested FFT, whereas in SYCL all the functions would already have to be present during compilation, so that's a fairly major change.

Does the performance of VkFFT depend on the fact that you can hardwire lots of constants when you produce code for a requested FFT, or do you think the algorithms can perform well even without custom code generation on the fly?

In any case I am really looking forward to your planned publication! I'm sure there are many interesting optimization details which are only hard to spot when looking at the source code.

**Comment by DTolm** [comment]
Hello,

as far as I understand, SYCL is an abstraction above CUDA, HIP, OpenCL and other backends. So, something that I am already doing myself. I decided not to use any of the available abstraction layers as this way I can have some unusual backends support (like Vulkan and potentially DirectX and Metal in the future).

The generated code is already fairly machine-like (it consists only of simple operations like additions and multiplications with some occasional if branching), so adding another abstraction layer should not have a considerable impact on final performance. 

GPU FFTs use plenty of different algorithms depending on the particular system. For example, strided and coalesced axes, multi-upload sequences, Bluestein algorithm sequences, R2C/R2R calculations, and things like zero-padding, convolutions and many other things create way too many different kernel structures suitable for static compilation. Trying to generalize them will have a toll on performance. 

I understood that the loss of time on start-up may be considerable when recompiling FFT plans code at every launch, so there is an option to pre-compile VkFFT code for a particular architecture, save it to disk and only load it at runtime. Does this work in the paradigm of SYCL? It should be possible to generate a limited pool of kernels for further reuse, similar to how other GPU libraries either ship precompiled binaries with their toolkits or generate them during toolkit compilation.

On a side note, why SYCL doesn't support runtime compilation, like NVRTC, HIPRTC, glslang compiler and base OpenCL?

**Comment by mreineck** [comment]
Thank you very much for the detailed reply!

I agree that attempting to generalize all the different possible algorithms into a single, static set of functions will probably reduce performance, and unfortunately this would be necessary for SYCL. So it's probably not the best idea to try and port VkFFT to it ...

> I understood that the loss of time on start-up may be considerable when recompiling FFT plans code at every launch, so there is an option to pre-compile VkFFT code for a particular architecture, save it to disk and only load it at runtime. Does this work in the paradigm of SYCL?

Unless I'm mistaken, no. The SYCL compilation process results in fully compiled code, both for CPU and GPU. So everything that is supposed to be executed on the device must be completely known at compile time.
This has the advantage that there will be no start-up overhead at runtime, but the disadvantage is that the amount of code for all possible FFT algorithms would be huge.

> On a side note, why SYCL doesn't support runtime compilation, like NVRTC, HIPRTC, glslang compiler and base OpenCL?

I'm not absolutely sure, but the main reason could be that the device code is written in full C++ (which is not a fun language to compile on the fly) and that, for example, the device code can refer to user-defined data types and functions that have been defined somewhere else in the rest of the program. This can be very convenient, since the programmer is not limited to native data types like CUDA etc.; but at the same time, this sacrifices the possibility for just--in-time compilation.

**Comment by mreineck** [comment]
No need to keep this open, I guess :-)

**Comment by DTolm** [comment]
> I agree that attempting to generalize all the different possible algorithms into a single, static set of functions will probably reduce performance, and unfortunately this would be necessary for SYCL. So it's probably not the best idea to try and port VkFFT to it ...

Well, the parallel algorithms are still there, and they will be similar, so it is just a question of implementation.

> I'm not absolutely sure, but the main reason could be that the device code is written in full C++ (which is not a fun language to compile on the fly) and that, for example, the device code can refer to user-defined data types and functions that have been defined somewhere else in the rest of the program. This can be very convenient, since the programmer is not limited to native data types like CUDA etc.; but at the same time, this sacrifices the possibility for just--in-time compilation.

Actually, won't SYCL use backend-specific libraries, like CUDA library collection? In this case it is possible to just use an interface to VkFFT without rewriting it for SYCL (as it supports at least three target SYCL backends).

**Comment by mreineck** [comment]
Sorry for the delay!

> Actually, won't SYCL use backend-specific libraries, like CUDA library collection? In this case it is possible to just use an interface to VkFFT without rewriting it for SYCL (as it supports at least three target SYCL backends).

Yes, that will certainly work to some extent. But as far as I understand, it currently requires using some implementation-dependent SYCL extensions, and this leads to the nasty situation where one needs to have slightly different code paths depending on both back-end *and* SYCL implementation. That would have been nice to avoid...

**Comment by mreineck** [comment]
Yes, the "real" end user will most likely not have to worry about this. But for the tool creator and mainainer it means a lot of effort for implementation and (since the SYCL implementations evolve) updating. For me personally it would most likely require more time than I can currently spend on such a project.

BTW, perhaps I should clarify this: I'm not officially involved with SYCL in any way, I'm just a (fairly new) user who thinks that an easy-to-use SYCL FFT would be a nice feature to have ;-)
