### ISSUE TITLE
Does VkFFT support multi-GPUs?

### ISSUE THREAD

**Issue by kongxiangcong** [DTolm/VkFFT#67]
Hello, I am interested in the features of vkfft with its large FFT length support. I want to implement multi-scale FFT on multi-GPUs (Nvidia). Does it support implementing in multi-GPUs in a node?

**Comment by DTolm** [comment]
Hello,

VkFFT currently is a single-GPU implementation. Of course, you can launch an instance of VkFFT at each GPU, but all the communications between them will not be handled by VkFFT. So far my understanding is that there is a separation in workload, as a distributed FFT library uses single-GPU implementations as a foundation. You can check heFFTe as one of those implementations.

Best regards,
Dmitrii

**Comment by kongxiangcong** [comment]
Thank you very much for your sincere reply!
Your answer has been solved my confusion and this issue could be closed.
Thanks!
