### ISSUE TITLE
2d r2c convolution in vulkan produces unwanted stripes with certain fft sizes

### ISSUE THREAD

**Issue by pborsutzki** [DTolm/VkFFT#75]
Hi,

I've now been experimenting for a while with vkFFT in vulkan and found some problems that seem to be fft size dependent.

I compared several sizes by computing an fft and ifft on some data, then comparing the input against the output. I found that these often do not match when ...
* x-axis is smaller than the y-axis.
* the y-axis is larger than half the x-axis and the y-axis contains prime factors other than 2 or 3, or just 3. Eg. 256x243 fails while 512x243 works, 256x237 fails while 512x237 works, 256x135 fails, etc.

When the output does not match the input, it seems to contain image spanning stripes.

When doing a similar comparison using the integrated convolution capability together with an identity kernel, there are more resolutions which do not produce the expected results. If these fail, the result often is just 0/black or also contains stripes. Example resolutions that fail for me are eg. 256x54, 256x75, 512x127, 512x128, 4096x1024, 8192x4096, 8192x8192 and many more. I haven't found a scheme behind that yet. Also with convolutions enabled, the x-axis has a bigger influence on working resolutions, eg. 6250x3888 fails while 5832x3888 works, 3082x1540 fails while 3080x1540 works.

As a lot of other resolutions work fine, I'd assume that my integration code is probably not the one to blame, but I am also not entirely sure of that yet. So can you easily confirm such problems using this description or do you need further input from my side?

Thanks!

**Comment by DTolm** [comment]
Hello,

I just tried all the mentioned systems on Intel UHD610 GPU in sample 15 (R2C+C2R, comparing against FFTW - similar to your test case), and everything seems to be within the appropriate error margins. So to further analyze the situation I will need more information on:

-the device VkFFT is run on. 
-max error and the respective value you encounter on the image data. Also having the results of sample 15 run on one of the failing systems can be useful.
-the generated kernels for one of the failing systems (use keepShaderCode=1 option and it will print them to console at execution)

We will get to convolution fixing after.

Best regards,
Dmitrii

**Comment by pborsutzki** [comment]
Hi,

I ran the experiments on an NVIDIA RTX A6000 (driver 472.98) using the latest vkFFT github master, built from source using Visual Studio 2022.

I just now ran sample 15 on that machine which shows large avg_differences of e.g. `6.72e+07` for some tests. Find the full output [here](https://github.com/DTolm/VkFFT/files/8796478/test_15_a6000_msvs17.txt). As a sanity check, I also ran the precompiled binaries from `VkFFT_Vulkan_release_v1.2.17` downloaded from github. This one shows a lot smaller differences for these tests ([full output](https://github.com/DTolm/VkFFT/files/8796485/test_15_a6000_prebuilt_1.2.17.txt)) making me wonder if the problem is compiler related or if it was introduced in the more recent commits.

About the image differences, they resemble tilted stripes through the image, depending on the resolution they are stronger or weaker. Example for 256x243:
| Input | Output (FFT->iFFT) | Normalized difference |
|-|-|-|
| ![fft_input](https://user-images.githubusercontent.com/1592151/170956600-22569670-2d8f-4da7-9e70-55983ea42e42.png) | ![fft_ifft_output](https://user-images.githubusercontent.com/1592151/170956755-66363993-6bfe-48e5-a2ca-fbe7e6c73c09.png) | ![fft_ifft_diff](https://user-images.githubusercontent.com/1592151/170956779-87d936b1-aba1-4a74-ad71-b2d889adc952.png) |

The shaders that are printed using `keepShaderCode=1` for the 256x243 sized [FFT are these](https://github.com/DTolm/VkFFT/files/8797103/fft_256x243.txt) and
[these for the according iFFT](https://github.com/DTolm/VkFFT/files/8797108/ifft_256x243.txt).
 
Though I can also see such problems using an NVIDIA P6000 ([test 15](https://github.com/DTolm/VkFFT/files/8797212/test_15_p6000_msvs17.txt)) and an NVIDIA T1000 ([test 15](https://github.com/DTolm/VkFFT/files/8797238/test_15_t1000_msvs17.txt)) in my own vkFFT integration and also using test 15 built from the latest master.

Thanks for your help!

**Comment by DTolm** [comment]
The issue with big R2C/C2R sequences in Vulkan backend is now fixed (I missed specifying tempBuffer range for unpacking kernels, so it was only Vulkan related issue).

As for the small kernel issue - I have checked your kernels and it seems that you use buffer sizes that don't match R2C template:
`
layout(std430, binding = 0) buffer DataIn{
        float inputs[249856];
};

layout(std430, binding = 1) buffer DataOut{
        vec2 outputs[124928];
};`

Here outputs must be in layout (256/2+1)*243*B as R2C output has N/2+1 size in the first dimension. 124928 doesn't match this (for B=3 it is much bigger and for B=4 it is a bit smaller). If the N/2+1 element is corrupted, stripes may occur (which you encounter). Can you check the memory layout you use?

Best regards,
Dmitrii

**Comment by pborsutzki** [comment]
Many thanks for the patch! Sample 15 now produces the same results as with the precompiled version from `VkFFT_Vulkan_release_v1.2.17`.

About the layouts/buffer sizes, it seems I mixed up width and height. I changed it to use `(width / 2 + 1) * height * channels`, where `size[0] = width` and `size[1] = height`, which seems to work fine so far.

I now am running my verification script again with convolutions enabled and currently it looks like convolutions are also working well, if I restrict the resolutions to multiples of prime factors <= 13. Is this in general a good idea e.g. for speed or should it just work anyways? As I have to pad my images anyways, adding a few pixels more usually doesn't hurt. Resolutions that failed for convolutions are for example 39x17, 42x19 and 65x31. These resolutions seem to work when just doing an fft and an ifft without convolutions.

Thanks for your help!

**Comment by DTolm** [comment]
> I now am running my verification script again with convolutions enabled and currently it looks like convolutions are also working well, if I restrict the resolutions to multiples of prime factors <= 13. Is this in general a good idea e.g. for speed or should it just work anyways? As I have to pad my images anyways, adding a few pixels more usually doesn't hurt. Resolutions that failed for convolutions are for example 39x17, 42x19 and 65x31. These resolutions seem to work when just doing an fft and an ifft without convolutions.

Convolutions don't work currently if the outermost FFT sequence has a length nondecomposable by primes up to 13. In general, primes <=13 are also considerably faster so padding (if possible) is beneficial. On smaller systems, it may also be beneficial to pad to sequences with lower primes, like 7, for better parallelism (this one will require testing to determine the performance though).

Best regards,
Dmitrii

**Comment by pborsutzki** [comment]
I'll just pad to multiples primes <= 13 then.

Thanks again for your help and the great library!
