### ISSUE TITLE
Clarification about benchmarks

### ISSUE THREAD

**Issue by hsnyder** [DTolm/VkFFT#77]
Thanks for writing VkFFT, this is incredible work!

I'm a bit confused about the benchmark results. In the comparisons between, say, cuFFT and VkFFT, is the Vulkan backend being used, or the CUDA backend (for VkFFT)? Are there any benchmarks that show the 3-way performance difference between: cuFFT, VkFFT-vulkan, and VkFFT-cuda? I'm mainly curious if the Vulkan backend performs similarly to the CUDA backend or not...

**Comment by DTolm** [comment]
Hello!

All backends have similar performance, aside from some cases that are dictated by the amount of shared memory exposed to the API (Vulkan and OpenCL on Nvidia GPUs can only use 48KB of it).

For more detailed information, you can check https://www.nvidia.com/en-us/on-demand/session/gtcspring21-s31300/ , where the comparison between cuFFT, VkFFT with Vulkan and VkFFT with CUDA backends is given and benchmark is explained.

Best regards,
Dmitrii

**Comment by hsnyder** [comment]
Hi Dmitrii,

Thank you very much for the quick and clear answer. I'm closing this issue. 

-Harris
