### ISSUE TITLE
Changing execution stream of existing plan

### ISSUE THREAD

**Issue by sbalint98** [DTolm/VkFFT#78]
Other FFT libraries offer options to change the stream the FFT plan is bound to. For example, in the case of rocFFT one can call `rocfft_execution_info_set_stream();` to change the stream a given handle refers to. Is it possible to do something similar with VkFFT in the case of the HIP backend?

**Comment by DTolm** [comment]
Hello, 

you can set stream during the configuration of the plan. If you want to change the stream after the initializeVkFFT call, you can change it in the internal app's copy of configuration: set app.configuration->stream pointer to your new stream pointer (and don't forget to set app.configuration->num_streams = 1 if you haven't done so during configuration).

Best regards,
Dmitrii

**Comment by sbalint98** [comment]
Hi, Thank you for the very quick help

**Comment by al42and** [comment]
Note to others doing the same: since VkFFT 1.3.5 (9a96811d specifically), `initializeVkFFT`/`setConfigurationVkFFT` makes a copy of all input pointers.

When you manually change `app.configuration.stream` as described above, you now need to unset it back to `nullptr` before calling `deleteVkFFT`. Otherwise, `deleteVkFFT` would call `free` on this pointer of yours, which can lead to double free or some other fun things.

**Comment by DTolm** [comment]
Yes, I will add a notice to all future releases about the change until the next major one. Technically, I think users generally should not modify the internal app structure themselves - it should be done through the launch parameters structure. 

As for the streams, thanks for bringing it up - I will add them to the parameters that can be updated at launch. If there are some other things that you think users may want to interact with - I will try to add them there too.

**Comment by al42and** [comment]
> Yes, I will add a notice to all future releases about the change until the next major one. Te

Not sure it's worth it, to be honest. If a user changes an internal structure directly, they are the only one to blame if things break :)

> As for the streams, thanks for bringing it up - I will add them to the parameters that can be updated at launch. If there are some other things that you think users may want to interact with - I will try to add them there too.

Thanks! Nothing else that I can think of.
