### ISSUE TITLE
Latest commit fails to compile

### ISSUE THREAD

**Issue by azonenberg** [DTolm/VkFFT#81]
Error:
```
In file included from /ceph/fast/home/azonenberg/code/scopehal-apps/lib/scopehal/VulkanInit.cpp:46:
/ceph/fast/home/azonenberg/code/scopehal-apps/lib/scopehal/../VkFFT/vkFFT/vkFFT.h: In function ‘VkFFTResult VkFFTPlanR2CMultiUploadDecomposition(VkFFTApplication*, VkFFTPlan*, uint64_t)’:
/ceph/fast/home/azonenberg/code/scopehal-apps/lib/scopehal/../VkFFT/vkFFT/vkFFT.h:33039:7: error: too many initializers for ‘const glslang_resource_t’ {aka ‘const glslang_resource_s’}
33039 |     } };
      |       ^
```

VkFFT.h (around line 33017):
```
				/* .maxMeshViewCountNV = */ 4,
				/* .max_mesh_output_vertices_ext = */ 256,
				/* .max_mesh_output_primitives_ext = */ 512,
				/* .max_mesh_work_group_size_x_ext = */ 32,
				/* .max_mesh_work_group_size_y_ext = */ 1,
				/* .max_mesh_work_group_size_z_ext = */ 1,
				/* .max_task_work_group_size_x_ext = */ 32,
				/* .max_task_work_group_size_y_ext = */ 1,
				/* .max_task_work_group_size_z_ext = */ 1,
				/* .maxMeshViewCountNV = */ 4,
				/* .maxDualSourceDrawBuffersEXT = */ 1,
```

glslang_c_interface.h:
```
    int max_mesh_view_count_nv;
    int maxDualSourceDrawBuffersEXT;

    glslang_limits_t limits;
} glslang_resource_t;
```

As far as I know I'm running the latest libglslang from the Vulkan SDK.

**Comment by azonenberg** [comment]
Looks like a copy-paste error, the _NV and _ext fields look to be identical and should live in the same location?

**Comment by azonenberg** [comment]
Upon closer inspection, https://github.com/KhronosGroup/glslang/blob/master/glslang/Include/glslang_c_interface.h#L144 appears to have the extra fields.

But the version of glslang_c_interface.h installed by the glslang-dev binary package, version 11.10.0~rc1-1lunarg20.04-1 (1.3.216 SDK) lacks it. That also seems to be the case with the 1.3.224 SDK.

Maybe add some kind of sizeof(glslang_resource_t) check so you don't use those fields if they're not present?

**Comment by DTolm** [comment]
Hello,

Indeed, the last update to glslang compiler introduced some new fields in glslang_resource_t. I have replaced full struct initialization with zero-initialization and only fill the old values now. This should work for both old and new versions.

Best regards,
Dmitrii

**Comment by azonenberg** [comment]
Yep, works fine for my SDK version.
