### ISSUE TITLE
VkFFT calculation issues (mostly non-radix)

### ISSUE THREAD

**Issue by vincefn** [DTolm/VkFFT#99]
Dear @DTolm, I am readying a new release of pyvkfft, and I am now doing systematic tests with the current VkFFT version.

The full test (not yet finished) running using CUDA on a A4500 can be seen at:
http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/cuda-A4500/pyvkfft-test.html

Many errors may be ignored (I may have made too many calculations in // ford 3D transforms, I need to check this), so I focus on the test failures rather than the errors.

All radix tests pass, except for two DCT1 transforms with a size of 675x675 when using a LUT for float32. The same error occurs on a V100. But not without forcing the LUT.

For non-radix dimensions (not sure which are Bluestein or Rader), there are more errors., there are:
* C2C 2D single precision also with LUT forced for various sizes 1348, 1796, 2245, 2313...
* R2C 2D with the same sizes also single precision with LUT
* R2C 1D out-of-place, double precision with size 6298 and 6308. I also get some isolated errors there (corruption, double free..) which are reported when the accuracy error occur. Ran again on a V100, the error occurs for a size 6110 instead
* R2C 1D in or out-of-place, single precision, with or without LUT with sizes 8738, 8772, 8806 etc..
*  a few DCT4 errors 

Thanks !

**Comment by vincefn** [comment]
In addition to the above calculation issues, I had a look at the errors. If i run sequentially (so no available memory issues) some transforms, e.g. an R2C 3D of size 284**3 in double precision out-of-place on a A4500, cuda-memcheck reports an error (the first tests with sizes 276 and 278 pass without issue):

```
(py311-pyvkfft) favre@scisoft13:~$ cuda-memcheck pyvkfft-test --systematic --backend pycuda --gpu a4500 --max-nb-tests 0  --ndim 3 --range 275 310 --r2c --bluestein --double --norm 1 --range-mb 0 4100
========= CUDA-MEMCHECK
test_systematic (pyvkfft.test.test_fft.TestFFTSystematic.test_systematic) ... Starting 12 tests...
  pycuda  R2C  (276,276,276) axes=      None ndim=   3    float64 lut=False inplace=0  norm=   1 C   FFT: n2=7.83e-16 ninf=9.85e-16 < 1.73e-14 (0.057) 1 iFFT: n2=7.57e-16 ninf=2.55e-15 < 1.73e-14 (0.147) 0   OK
  pycuda  R2C  (278,278,278) axes=      None ndim=   3    float64 lut=False inplace=0  norm=   1 C   FFT: n2=1.27e-15 ninf=1.29e-15 < 1.73e-14 (0.075) 1 iFFT: n2=1.33e-15 ninf=3.77e-15 < 1.73e-14 (0.218) 0   OK
========= Invalid __global__ read of size 16
=========     at 0x000001e0 in VkFFT_main
=========     by thread (1,47,0) in block (0,70,281)
=========     Address 0x7f1fcec4efb0 is out of bounds
=========     Device Frame:VkFFT_main (VkFFT_main : 0x1e0)
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 [0x2083aa]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/lib/python3.11/site-packages/pyvkfft/_vkfft_cuda.cpython-311-x86_64-linux-gnu.so [0xbd84]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/lib/python3.11/site-packages/pyvkfft/_vkfft_cuda.cpython-311-x86_64-linux-gnu.so [0x21273]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/lib/python3.11/site-packages/pyvkfft/_vkfft_cuda.cpython-311-x86_64-linux-gnu.so (ifft + 0x68) [0xb0ef8]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/lib/python3.11/lib-dynload/../../libffi.so.8 [0x6a4a]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/lib/python3.11/lib-dynload/../../libffi.so.8 [0x5fea]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/lib/python3.11/lib-dynload/_ctypes.cpython-311-x86_64-linux-gnu.so [0x12da0]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/lib/python3.11/lib-dynload/_ctypes.cpython-311-x86_64-linux-gnu.so [0x1242b]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/bin/python3.11 (_PyObject_MakeTpCall + 0x27b) [0x1dd8cb]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/bin/python3.11 (_PyEval_EvalFrameDefault + 0x319e) [0x1ed69e]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/bin/python3.11 (_PyFunction_Vectorcall + 0x361) [0x214081]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/bin/python3.11 (PyObject_Call + 0x9d) [0x21f01d]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/bin/python3.11 (_PyEval_EvalFrameDefault + 0x496f) [0x1eee6f]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/bin/python3.11 (_PyFunction_Vectorcall + 0x161) [0x213e81]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/bin/python3.11 (_PyEval_EvalFrameDefault + 0x496f) [0x1eee6f]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/bin/python3.11 (_PyFunction_Vectorcall + 0x161) [0x213e81]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/bin/python3.11 (_PyEval_EvalFrameDefault + 0x496f) [0x1eee6f]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/bin/python3.11 [0x1e61fb]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/bin/python3.11 (PyEval_EvalCode + 0x9f) [0x2b09af]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/bin/python3.11 [0x2d3479]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/bin/python3.11 [0x2cf724]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/bin/python3.11 (PyRun_StringFlags + 0x63) [0x2c16e3]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/bin/python3.11 (PyRun_SimpleStringFlags + 0x3d) [0x2c158d]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/bin/python3.11 (Py_RunMain + 0x3ef) [0x2de16f]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/bin/python3.11 (Py_BytesMain + 0x39) [0x29f3f9]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xea) [0x23d0a]
=========     Host Frame:/home/esrf/favre/miniconda3/envs/py311-pyvkfft/bin/python3.11 [0x29f2a1]
=========
```

**Comment by DTolm** [comment]
Hello, 

I have fixed all the mentioned issues except the memory-related ones. I could not reproduce corruption and double free yet. pyvkfft passes 284^3 test without cuda memcheck errors for me (on 3070, which is also compute 8.6 device). All the R2C systems (6298, 6308 and 6110) also work from the sample 15 test in VkFFT.

Best regards,
Dmitrii

**Comment by vincefn** [comment]
Thanks a lot ! I've started the tests again on different cards at:
http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/pyvkfft-test-2023-01-08-a4500cu/pyvkfft-test.html
http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/pyvkfft-test-2023-01-08-p6000cl/pyvkfft-test.html
http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/pyvkfft-test-2023-01-08-v100cu/pyvkfft-test.html

**Comment by DTolm** [comment]
@vincefn I have fixed the 8 R2C systems that failed (the change should not affect other systems - it was related to an off case where VkFFT did not switch to even R2C algorithm in Bluestein after finding primes that can't be done with Rader algorithm).

Best regards,
Dmitrii

**Comment by vincefn** [comment]
Thanks ! I've re-launched the test, they'll update at:
http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/pyvkfft-test-2023-01-08b-a4500cu/pyvkfft-test.html
http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/pyvkfft-test-2023-01-08b-p6000cl/pyvkfft-test.html
http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/pyvkfft-test-2023-01-08b-v100cu/pyvkfft-test.html

Besides the R2C errors, in the previous batch there was a lone C2C error:
```
pyvkfft-test --systematic --backend pycuda --gpu v100 --max-nb-tests 0 --nproc 20 --ndim 1 --range 2 10000 --bluestein --norm 1 --range-mb 0 4100

FAILURES:

======================================================================
test_systematic  (backend='pycuda', shape=(6140,), ndim=1, dtype=dtype('float32'), norm=1, use_lut=False, inplace=False, r2c=False, dct=False, fstride=False) [pyvkfft.test.test_fft.TestFFTSystematic]:
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/multipath-shares/scisoft/users/favre/dev/pynx-py38-power9-env/lib/python3.8/site-packages/pyvkfft/test/test_fft.py", line 725, in test_systematic
    self.assertTrue(ni < tol, "Accuracy mismatch after FFT, n2=%8e ni=%8e>%8e" % (n2, ni, tol))
AssertionError: False is not true : Accuracy mismatch after FFT, n2=6.643175e-01 ni=1.011326e+00>7.788168e-06
```

..but this happened only on the V100 (I tested on a P6000 and a Titan V). I tested after updating vkfft (though it should not affect that C2C test) in a more isolated way but could not reproduce - we'll see if this happens again.

**Comment by DTolm** [comment]
@vincefn I don't know why relaunch full test, this fix won't affect the previous tests and it is more important to know the edge cases that latter tests reveal?

As for the lone error - similar errors on A4500 did not appear this time. Maybe something related to drivers, I have no ideas so far?

**Comment by vincefn** [comment]
I always relaunch full tests as a matter of principle when I am preparing for a release. Even if in that case the changeset is very small, it' always a good policy to run the full test suite. Also because I can keep all test results in a single place to display them. And it gives us time to sleep :-)

As for the V100 error, hard to say what happened, it happened on an 'old' installation with cuda 10.1, driver 418.126.02 - it's a power9 machine (not an architecture very well supported by nvidia). We'll see if that happens again.

**Comment by DTolm** [comment]
@vincefn I think I solved the out-of-bounds access in R2C, can you verify this, as my Windows build was not able to detect it?

**Comment by DTolm** [comment]
@vincefn sure, I will tag it after we are certain that there are no more failing cases (when the run completes).

**Comment by vincefn** [comment]
So far it looks good:

http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/pyvkfft-test-2023-01-10-v100cu/pyvkfft-test.html
http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/pyvkfft-test-2023-01-10-a4500cu/pyvkfft-test.html
http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/pyvkfft-test-2023-01-10-p6000cl/pyvkfft-test.html

Just 3 timeouts on the opencl 3D transforms with the largest sizes, and this is probably harmless.

**Comment by vincefn** [comment]
Dear @DTolm, another specific set of errors seem to occur with the OpenCL 2D R2C transform (double precision, in and out-of-place), starting around size 2942x2942, first with an OUT_OF_RESOURCES error then VKFFT_ERROR_FAILED_TO_COMPILE_PROGRAM on the subsequent sizes.

This happens with OpenCL on the P6000 test, but I also reproduce it on a Titan V and a GTX 1080 Ti (using driver 470, cuda 11.4). I could not reproduce it on an A2000.

```
pyvkfft-test --systematic --backend pyopencl --gpu p6000 --max-nb-tests 0 --nproc 16 --ndim 2 --range 2 4500 --r2c --bluestein --inplace --double --norm 0 --range-mb 0 4100 --opencl_platform nvidia

ERRORS:

======================================================================
test_systematic  (backend='pyopencl', shape=(2942, 2942), ndim=2, dtype=dtype('float64'), norm=0, use_lut=False, inplace=True, r2c=True, dct=False, fstride=False) [pyvkfft.test.test_fft.TestFFTSystematic]:
----------------------------------------------------------------------
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/esrf/favre/miniconda3/envs/py311-pyvkfft/lib/python3.11/site-packages/pyvkfft/accuracy.py", line 532, in test_accuracy_kwargs
    t = test_accuracy(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/esrf/favre/miniconda3/envs/py311-pyvkfft/lib/python3.11/site-packages/pyvkfft/accuracy.py", line 481, in test_accuracy
    tmp = np.take(d1_gpu.get(), range(d1_gpu.shape[fast_axis] - 2), axis=fast_axis)
                  ^^^^^^^^^^^^
  File "/home/esrf/favre/miniconda3/envs/py311-pyvkfft/lib/python3.11/site-packages/pyopencl/array.py", line 921, in get
    ary, event1 = self._get(queue=queue, ary=ary, async_=async_, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/esrf/favre/miniconda3/envs/py311-pyvkfft/lib/python3.11/site-packages/pyopencl/array.py", line 880, in _get
    event1 = cl.enqueue_copy(queue, ary, self.base_data,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/esrf/favre/miniconda3/envs/py311-pyvkfft/lib/python3.11/site-packages/pyopencl/__init__.py", line 2009, in enqueue_copy
    return _cl._enqueue_read_buffer(queue, src, dest, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyopencl._cl.RuntimeError: clEnqueueReadBuffer failed: OUT_OF_RESOURCES

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/esrf/favre/miniconda3/envs/py311-pyvkfft/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/esrf/favre/miniconda3/envs/py311-pyvkfft/lib/python3.11/site-packages/pyvkfft/accuracy.py", line 537, in test_accuracy_kwargs
    raise RuntimeError("An OpenCL RuntimeError was encountered")
RuntimeError: An OpenCL RuntimeError was encountered
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/esrf/favre/miniconda3/envs/py311-pyvkfft/lib/python3.11/site-packages/pyvkfft/test/test_fft.py", line 681, in test_systematic
    res = results.next(timeout=self.timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/esrf/favre/miniconda3/envs/py311-pyvkfft/lib/python3.11/multiprocessing/pool.py", line 873, in next
    raise value
RuntimeError: An OpenCL RuntimeError was encountered

======================================================================
test_systematic  (backend='pyopencl', shape=(2974, 2974), ndim=2, dtype=dtype('float64'), norm=0, use_lut=False, inplace=True, r2c=True, dct=False, fstride=False) [pyvkfft.test.test_fft.TestFFTSystematic]:
----------------------------------------------------------------------
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/esrf/favre/miniconda3/envs/py311-pyvkfft/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/esrf/favre/miniconda3/envs/py311-pyvkfft/lib/python3.11/site-packages/pyvkfft/accuracy.py", line 532, in test_accuracy_kwargs
    t = test_accuracy(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/esrf/favre/miniconda3/envs/py311-pyvkfft/lib/python3.11/site-packages/pyvkfft/accuracy.py", line 283, in test_accuracy
    app = clVkFFTApp(d0.shape, d0.dtype, queue, ndim=ndim, norm=norm,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/esrf/favre/miniconda3/envs/py311-pyvkfft/lib/python3.11/site-packages/pyvkfft/opencl.py", line 118, in __init__
    check_vkfft_result(res, shape, dtype, ndim, inplace, norm, r2c, dct, axes, "opencl:%s:%s" %
  File "/home/esrf/favre/miniconda3/envs/py311-pyvkfft/lib/python3.11/site-packages/pyvkfft/base.py", line 425, in check_vkfft_result
    raise RuntimeError("VkFFT error %d: %s %s" % (res, r.name, s))
RuntimeError: VkFFT error 4031: VKFFT_ERROR_FAILED_TO_COMPILE_PROGRAM R2C (2974,2974+2) float64 2D inplace [opencl:NVIDIA CUDA:Quadro P6000]
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/esrf/favre/miniconda3/envs/py311-pyvkfft/lib/python3.11/site-packages/pyvkfft/test/test_fft.py", line 681, in test_systematic
    res = results.next(timeout=self.timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/esrf/favre/miniconda3/envs/py311-pyvkfft/lib/python3.11/multiprocessing/pool.py", line 873, in next
    raise value
RuntimeError: VkFFT error 4031: VKFFT_ERROR_FAILED_TO_COMPILE_PROGRAM R2C (2974,2974+2) float64 2D inplace [opencl:NVIDIA CUDA:Quadro P6000]
...
```

There are also a few errors on the V100 for C2C 1D non-radix transforms (approximately sizes 6128, 6129 ..) but this is on an old driver with cuda 10.1, and the exact size where the error occurs varies a bit. I'll try to reproduce this witha more recent driver.

**Comment by vincefn** [comment]
@DTolm if I try sequentially (using --nproc 1) the same errors are reported, with the kernel written on the output indicating Vkfft detected an error, starting with OUT_OF_RESOURCES.

(regarding the V100 C2C transforms the test run fin with a V100 on a x86 host with a recent (11.7) driver, so these can be ignored)

**Comment by DTolm** [comment]
@vincefn I have found the error and fixed it (VkFFT calculated the used shared memory size incorrectly and allocated less than needed), these R2C transforms should work now.

**Comment by vincefn** [comment]
@DTolm these R2C errors look indeed fixed (I ran individual tests), but this seems to have introduced issues for DCT2 and DCT3 2D and 3D transforms, at least on a V100 (CUDA) and P6000 (opencl):
http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/pyvkfft-test-2023-01-12-p6000cl/pyvkfft-test.html
http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/pyvkfft-test-2023-01-12-v100cu/pyvkfft-test.html

the A4500/cuda looks OK:
http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/pyvkfft-test-2023-01-12-a4500cu/pyvkfft-test.html

**Comment by DTolm** [comment]
@vincefn should be fixed now, but I again could not reproduce the error on my machine to certainly say in advance that it is fixed in all places.

**Comment by vincefn** [comment]
Thanks a lot @DTolm ! The basic test and the DCT2&3 tests which failed seem to work OK now.

I have relaunched the test suites:
http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/pyvkfft-test-2023-01-13-a4500cu/pyvkfft-test.html
http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/pyvkfft-test-2023-01-13-v100cu/pyvkfft-test.html
http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/pyvkfft-test-2023-01-13-p6000cl/pyvkfft-test.html

**Comment by vincefn** [comment]
I have relaunched the tests after the latest fix (nice find with the 2D 2988 Sophie Germain prime error !):
http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/pyvkfft-test-2023-01-14-a4500cu/pyvkfft-test.html
http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/pyvkfft-test-2023-01-14-v100cu/pyvkfft-test.html
http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/pyvkfft-test-2023-01-14-p6000cl/pyvkfft-test.html

Regarding the v100 failures/errors, I have re-tested them on another v100 on a x86 system with cuda 11.6 driver, without issue.

**Comment by DTolm** [comment]
With so many algorithms working together the likelihood of some edge cases appearing is big. Thank you for your extensive testing, as it catches these cases.

**Comment by vincefn** [comment]
@DTolm - thanks a lot for the quick fixes. I'm happy to do the testing, this is important for us as we started using (py)vkfft in production last year, and it gives a nice performance boost !

All tests are finished now , there was just one timeout on the A4500 (not reproduced when re-testing), and the opencl P6000 tests went OK. The V100 issues are apparently due to the old driver.

So this looks good for a new release version which I can use for pyvkfft if you agree !

**Comment by DTolm** [comment]
@vincefn There was an additional issue found with the custom strides multi-upload scheme that allocated less memory than needed. It should also be fixed now and I did a version increment. I guess if the tests pass now (and the issue is fixed), I will upload a new set of binaries/this can be used as a release version.

**Comment by vincefn** [comment]
Looks like I should add to the testsuite systematic tests with strides, i.e. 1D transforms on the y-axis for 2D arrays, on the z-axis for 3D arrays, and 2D transforms on the z and y-axes for a 3D array.
So far I only do that with the quick test which only uses sizes of 34 or 808.

**Comment by vincefn** [comment]
Yes, the tests can't really be exhaustive. But skipping one axis for a transform is not unusual, so it would be good to test that as well. It's only for C2C thankfully. I can start by adding this to the non-systematic test.

I did not reproduce the #101 error using a (4200,2) array or a (4200, 1024) one  transformed only on the y-axis (4200) ? That's with all possible C2C transforms (in/out-of-place, single and double precision). 

I'm not sure #101 can be reproduced in pyvkfft since #101 uses an array (ny, nx) transformed along y using strides > nx (I don't really understand how that can be used if fact, I get stride=nx but otherwise ?).

**Comment by DTolm** [comment]
It was related to incorrect tempBuffer size calculation with strides - for example, a case (4200, 8192) with a stride 4204 would have failed. But I have fixed it in the last update. 

You can see why the strides are useful in #100.

**Comment by vincefn** [comment]
All tests finished  with the latest version
http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/pyvkfft-test-2023-01-16-a4500cu/pyvkfft-test.html
http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/pyvkfft-test-2023-01-16-v100cu/pyvkfft-test.html
http://ftp.esrf.fr/pub/scisoft/PyNX/pyvkfft-test/pyvkfft-test-2023-01-16-p6000cl/pyvkfft-test.html

a few timeouts, apparently dues to the heavy load (maybe some other job using memory), which cannot be reproduced.

So that's good for me, I'll use this for a release. Thanks !

**Comment by DTolm** [comment]
Sounds good!

**Comment by vincefn** [comment]
One last (unrelated) thing, I finally ran a full 2D benchmark (pyvkfft cuda, opencl, cuFFT and clfft) on an A40. Here is the radix<=13 test:

![benchmark-2DFFTNVIDIA_CUDA:NVIDIA_A40--radix13-Linux-5 4 0-137-generic-x86_64-with-glibc2 31-gpu4-02-2023-01-18-10h08](https://user-images.githubusercontent.com/4380511/213420226-62c378eb-dbcc-47e8-842f-987f8389e28a.png)

This is the only case where cuFFT keeps up, or is slightly better, than pyvkfft (except radix-11 and 13). All other GPUs (V100, A4500, ..) give pyvkfft a larger advantage beyond 1024 length. I guess nvidia improved tuning for this architecture and the larger caches/shared memory ?

**Comment by DTolm** [comment]
Small systems are prone to cache reuse - so results there are less representative of how the library will behave in the real workload. 

For larger systems, OpenCL works worse than CUDA due to the fact that it can only expose 48KB of static shared memory per thread block - on A40 CUDA can use the full 96KB. This is seen for systems between 1536 and 3072. 

Other than that, it seems to have pretty even bandwidth-limited results for these simple cases (primes up to 7). You can also try CUDA 12, Nvidia made some more improvements there - like making their Rader's algorithm version available to consumer-level GPUs.
